 [
        'id' => 51,
        'format' => 3,
        'test_type' => 'NonVerbal',
        'question' => '<img src=storage/questions/51_q.JPG>',
        'answer' => '<img src=storage/questions/51_b.JPG>',
        'ch1' => '<img src=storage/questions/51_a.JPG>',
        'ch2' => '<img src=storage/questions/51_b.JPG>',
        'ch3' => '<img src=storage/questions/51_c.JPG>',
        'ch4' => '<img src=storage/questions/51_d.jpg>',
        'ch5' => '<img src=storage/questions/51_e.JPG>',
        'qtype' => 'Quantitative Reasoning',
    ],
    [
        'id' => 52,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/52_q.jpg>',
        'answer' => '<img src=storage/questions/52_c.JPG>',
        'ch1' => '<img src=storage/questions/52_a.jpg>',
        'ch2' => '<img src=storage/questions/52_b.jpg>',
        'ch3' => '<img src=storage/questions/52_c.JPG>',
        'ch4' => '<img src=storage/questions/52_d.jpg>',
        'ch5' => '<img src=storage/questions/52_e.JPG>',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 53,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'There can be no message if there is no ----',
        'answer' => 'thought',
        'ch1' => 'word',
        'ch2' => 'note',
        'ch3' => 'messenger',
        'ch4' => 'thought',
        'ch5' => 'pencil',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 54,
        'format' => 3,
        'test_type' => 'NonVerbal',
        'question' => '<img src=storage/questions/54_q.jpg>',
        'answer' => '<img src=storage/questions/54_a.jpg>',
        'ch1' => '<img src=storage/questions/54_a.jpg>',
        'ch2' => '<img src=storage/questions/54_b.jpg>',
        'ch3' => '<img src=storage/questions/54_c.jpg>',
        'ch4' => '<img src=storage/questions/54_d.JPG>',
        'ch5' => '<img src=storage/questions/54_e.JPG>',
        'qtype' => 'Figural Reasoning',
    ],
    [
        'id' => 55,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'Choose the words that <i>best</i> complete this sentence: <br> The evidence against him was ________ so the charge were _________',
        'answer' => 'unsupported ---- dismissed',
        'ch1' => 'convincing ---- dropped',
        'ch2' => 'feeble ---- extended',
        'ch3' => 'overwhelming ---- reduced',
        'ch4' => 'damaging ---- withdrawn',
        'ch5' => 'unsupported ---- dismissed',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 56,
        'format' => 3,
        'test_type' => 'NonVerbal',
        'question' => '<img src=storage/questions/55_q.JPG>',
        'answer' => '<img src=storage/questions/55_b.JPG>',
        'ch1' => '<img src=storage/questions/55_a.JPG>',
        'ch2' => '<img src=storage/questions/55_b.JPG>',
        'ch3' => '<img src=storage/questions/55_c.JPG>',
        'ch4' => '<img src=storage/questions/55_d.JPG>',
        'ch5' => '<img src=storage/questions/55_e.JPG>',
        'qtype' => 'Figural Reasoning',
    ],
    [
        'id' => 57,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'The opposite of <b>scarcity</b> is ----',
        'answer' => 'abundance',
        'ch1' => 'necessity',
        'ch2' => 'bonus',
        'ch3' => 'privilage',
        'ch4' => 'abundance',
        'ch5' => 'expansion',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 58,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'In a foreign language <b>tana dona meka</b> means <b>very cold water, tana neta</b> means <b>hot water,</b> and <b>dona bela</b> means <b>very good.</b> Whice word means <b>cold</b>?',
        'answer' => 'meka',
        'ch1' => 'dona',
        'ch2' => 'neta',
        'ch3' => 'tana',
        'ch4' => 'bela',
        'ch5' => 'meka',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 59,
        'format' => 3,
        'test_type' => 'NonVerbal',
        'question' => '<img src=storage/questions/59_q.JPG>',
        'answer' => '<img src=storage/questions/59_d.jpg>',
        'ch1' => '<img src=storage/questions/59_a.JPG>',
        'ch2' => '<img src=storage/questions/59_b.JPG>',
        'ch3' => '<img src=storage/questions/59_c.JPG>',
        'ch4' => '<img src=storage/questions/59_d.jpg>',
        'ch5' => '<img src=storage/questions/59_e.jpg>',
        'qtype' => 'Figural Reasoning',
    ],
    [
        'id' => 60,
        'format' => 1,
        'test_type' => 'NonVerbal',
        'question' => 'What number comes next in this series?   5    11    16    20    23    ?',
        'answer' => '25',
        'ch1' => '24',
        'ch2' => '25',
        'ch3' => '27',
        'ch4' => '28',
        'ch5' => '29',
        'qtype' => 'Quantitative Reasoning',
    ],
    [
        'id' => 61,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'Which word does <i>not</i> go with the other four?',
        'answer' => 'frightened',
        'ch1' => 'dangerous',
        'ch2' => 'risky',
        'ch3' => 'hazardous',
        'ch4' => 'unsafe',
        'ch5' => 'frightened',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 62,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/62_q.JPG>',
        'answer' => '<img src=storage/questions/62_b.JPG>',
        'ch1' => '<img src=storage/questions/62_a.JPG>',
        'ch2' => '<img src=storage/questions/62_b.JPG>',
        'ch3' => '<img src=storage/questions/62_c.JPG>',
        'ch4' => '<img src=storage/questions/62_d.JPG>',
        'ch5' => '<img src=storage/questions/62_e.JPG>',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 63,
        'format' => 3,
        'test_type' => 'NonVerbal',
        'question' => '<img src=storage/questions/63_q.JPG>',
        'answer' => '<img src=storage/questions/63_b.jpg>',
        'ch1' => '<img src=storage/questions/63_a.JPG>',
        'ch2' => '<img src=storage/questions/63_b.jpg>',
        'ch3' => '<img src=storage/questions/63_c.JPG>',
        'ch4' => '<img src=storage/questions/63_d.JPG>',
        'ch5' => '<img src=storage/questions/63_e.JPG>',
        'qtype' => 'Figural Reasoning',
    ],
    [
        'id' => 64,
        'format' => 3,
        'test_type' => 'NonVerbal',
        'question' => '<img src=storage/questions/64_q.JPG>',
        'answer' => '<img src=storage/questions/64_c.jpg>',
        'ch1' => '<img src=storage/questions/64_a.JPG>',
        'ch2' => '<img src=storage/questions/64_b.JPG>',
        'ch3' => '<img src=storage/questions/64_c.jpg>',
        'ch4' => '<img src=storage/questions/64_d.jpg>',
        'ch5' => '<img src=storage/questions/64_e.JPG>',
        'qtype' => 'Quantitative Reasoning',
    ],
    [
        'id' => 65,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'A cloud is always ----',
        'answer' => 'humid',
        'ch1' => 'humid',
        'ch2' => 'fluffy',
        'ch3' => 'white',
        'ch4' => 'big',
        'ch5' => 'high',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 66,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/66_q.JPG>',
        'answer' => '<img src=storage/questions/66_d.JPG>',
        'ch1' => '<img src=storage/questions/66_a.JPG>',
        'ch2' => '<img src=storage/questions/66_b.JPG>',
        'ch3' => '<img src=storage/questions/66_c.JPG>',
        'ch4' => '<img src=storage/questions/66_d.JPG>',
        'ch5' => '<img src=storage/questions/66_e.jpg>',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 67,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/67_q.jpg>',
        'answer' => '<img src=storage/questions/67_e.jpg>',
        'ch1' => '<img src=storage/questions/67_a.JPG>',
        'ch2' => '<img src=storage/questions/67_b.JPG>',
        'ch3' => '<img src=storage/questions/67_c.JPG>',
        'ch4' => '<img src=storage/questions/67_d.jpg>',
        'ch5' => '<img src=storage/questions/67_e.jpg>',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 68,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/68_q.JPG>',
        'answer' => '<img src=storage/questions/68_e.jpg>',
        'ch1' => '<img src=storage/questions/68_a.JPG>',
        'ch2' => '<img src=storage/questions/68_b.JPG>',
        'ch3' => '<img src=storage/questions/68_c.JPG>',
        'ch4' => '<img src=storage/questions/68_d.jpg>',
        'ch5' => '<img src=storage/questions/68_e.jpg>',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 69,
        'format' => 3,
        'test_type' => 'NonVerbal',
        'question' => '<img src=storage/questions/69_q.jpg>',
        'answer' => '<img src=storage/questions/69_c.JPG>',
        'ch1' => '<img src=storage/questions/69_a.JPG>',
        'ch2' => '<img src=storage/questions/69_b.jpg>',
        'ch3' => '<img src=storage/questions/69_c.JPG>',
        'ch4' => '<img src=storage/questions/69_d.JPG>',
        'ch5' => '<img src=storage/questions/69_e.JPG>',
        'qtype' => 'Quantitative Reasoning',
    ],
    [
        'id' => 70,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/70_q.jpg>',
        'answer' => '<img src=storage/questions/70_a.jpg>',
        'ch1' => '<img src=storage/questions/70_a.jpg>',
        'ch2' => '<img src=storage/questions/70_b.jpg>',
        'ch3' => '<img src=storage/questions/70_c.jpg>',
        'ch4' => '<img src=storage/questions/70_d.jpg>',
        'ch5' => '<img src=storage/questions/70_e.jpg>',
        'qtype' => 'Verbal Reasoning',
    ],
    [
        'id' => 71,
        'format' => 1,
        'test_type' => 'NonVerbal',
        'question' => 'what number divided by three is equal to ten plus two?',
        'answer' => '36',
        'ch1' => '12',
        'ch2' => '13',
        'ch3' => '24',
        'ch4' => '30',
        'ch5' => '36',
        'qtype' => 'Quantitative Reasoning',
    ],
    [
        'id' => 72,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'Choose the words that <i>best</i> complete this sentence: <br> Although Jamie s grades were _________, her parents were ________',
        'answer' => 'acceptable ---- disappointed',
        'ch1' => 'excellent ---- delighted',
        'ch2' => 'terrible ---- furious',
        'ch3' => 'poor ---- dissatisfied',
        'ch4' => 'acceptable ---- disappointed',
        'ch5' => 'superior ---- interested',
        'qtype' => 'Verbal Comprehension',

    ],
