<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('questions')->insert([

            [
                'id'        => 1,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'Choose the words that <i>best</i> complete this sentence: <br> _________ I was nervous, I had a _________',
                'answer'    => 'ch4',
                'ch1'       => 'When --- sad',
                'ch2'       => 'After --- jittery',
                'ch3'       => 'If ---- reasonable',
                'ch4'       => 'Although --- quiet',
                'ch5'       => 'Where --- humorous',
                'qtype'     => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 2,
                'format'    => 'photo',
                'test_type' => 'Verbal',
                'question'  => '<img src=storage/questions/2_q.jpg>',
                'answer'    => 'ch5',
                'ch1'       => '<img src=storage/questions/2_a.jpg>',
                'ch2'       => '<img src=storage/questions/2_b.jpg>',
                'ch3'       => '<img src=storage/questions/2_c.jpg>',
                'ch4'       => '<img src=storage/questions/2_d.jpg>',
                'ch5'       => '<img src=storage/questions/2_e.jpg>',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 3,
                'format'    => 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/3_q.jpg>',
                'answer'    => 'ch4',
                'ch1'       => '<img src=storage/questions/3_a.jpg>',
                'ch2'       => '<img src=storage/questions/3_b.jpg>',
                'ch3'       => '<img src=storage/questions/3_c.jpg>',
                'ch4'       => '<img src=storage/questions/3_d.jpg>',
                'ch5'       => '<img src=storage/questions/3_e.jpg>',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 4,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/4_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/4_a.jpg>',
                'ch2'       => '<img src=storage/questions/4_b.jpg>',
                'ch3'       => '<img src=storage/questions/4_c.jpg>',
                'ch4'       => '<img src=storage/questions/4_d.jpg>',
                'ch5'       => '<img src=storage/questions/4_e.jpg>',
                'qtype'     => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 5,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => '<b>First</b> is to original as <b>only</b> is to ---',
                'answer'    => 'ch2',
                'ch1'       => 'special',
                'ch2'       => 'unique',
                'ch3'       => 'expensive',
                'ch4'       => 'many',
                'ch5'       => 'last',
                'qtype'     => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 6,
                'format'=> 'photo',
                'test_type' => 'Verbal',
                'question'  => '<img src=storage/questions/6_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/6_a.jpg>',
                'ch2'       => '<img src=storage/questions/6_b.jpg>',
                'ch3'       => '<img src=storage/questions/6_c.jpg>',
                'ch4'       => '<img src=storage/questions/6_d.jpg>',
                'ch5'       => '<img src=storage/questions/6_e.jpg>',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 7,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/7_q.jpg>',
                'answer'    => 'ch5',
                'ch1'       => '<img src=storage/questions/7_a.jpg>',
                'ch2'       => '<img src=storage/questions/7_b.jpg>',
                'ch3'       => '<img src=storage/questions/7_c.jpg>',
                'ch4'       => '<img src=storage/questions/7_d.jpg>',
                'ch5'       => '<img src=storage/questions/7_e.jpg>',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 8,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/8_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/8_a.jpg>',
                'ch2'       => '<img src=storage/questions/8_b.jpg>',
                'ch3'       => '<img src=storage/questions/8_c.jpg>',
                'ch4'       => '<img src=storage/questions/8_d.jpg>',
                'ch5'       => '<img src=storage/questions/8_e.jpg>',
                'qtype'     => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 9,
                'format'    => 'text',
                'test_type' => 'non-verbal',
                'question'  => 'What number comes next in this series?   1    6    10    13    15    ?',
                'answer'    => 'ch2',
                'ch1'       => '14',
                'ch2'       => '16',
                'ch3'       => '17',
                'ch4'       => '18',
                'ch5'       => '19',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 10,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'The opposite of <b>confinement</b> is ----',
                'answer'    => 'ch5',
                'ch1'       => 'recognition',
                'ch2'       => 'satisfaction',
                'ch3'       => 'cooperation',
                'ch4'       => 'dedication',
                'ch5'       => 'freedom',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

                [
                'id'        => 11,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'Which word does <i>not</i> go with the other four?',
                'answer'    => 'ch2',
                'ch1'       => 'honest',
                'ch2'       => 'polite',
                'ch3'       => 'truthful',
                'ch4'       => 'open',
                'ch5'       => 'frank',
                'qtype'     => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 12,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/12_q.jpg>',
                'answer'    => 'ch4',
                'ch1'       => '<img src=storage/questions/12_a.jpg>',
                'ch2'       => '<img src=storage/questions/12_b.jpg>',
                'ch3'       => '<img src=storage/questions/12_c.jpg>',
                'ch4'       => '<img src=storage/questions/12_d.jpg>',
                'ch5'       => '<img src=storage/questions/12_e.jpg>',
                'qtype'     => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 13,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'There are five houses in a row. One house is gree. Two yellow houses are next to each other. The end house is red. The middle house is blue. What colors are the houses that are farthest apart?',
                'answer'    => 'ch1',
                'ch1'       => 'Red and yellow',
                'ch2'       => 'Red and blue',
                'ch3'       => 'Yellow and blue',
                'ch4'       => 'Green and yellow',
                'ch5'       => 'Blue and green',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 14,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'An enclosure always has ---',
                'answer'    => 'ch3',
                'ch1'       => 'an entrance',
                'ch2'       => 'ventilation',
                'ch3'       => 'sides',
                'ch4'       => 'a roof',
                'ch5'       => 'windows',
                'qtype'     => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 15,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'Choose the word that <i>best</i> completes this sentence: <br> Faulty reasoning generally results in _________ conclusions.',
                'answer'    => 'ch4',
                'ch1'       => 'intelligent',
                'ch2'       => 'valid',
                'ch3'       => 'eccentric',
                'ch4'       => 'erroneous',
                'ch5'       => 'offensive',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 16,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/16_q.jpg>',
                'answer'    => 'ch4',
                'ch1'       => '<img src=storage/questions/16_a.jpg>',
                'ch2'       => '<img src=storage/questions/16_b.jpg>',
                'ch3'       => '<img src=storage/questions/16_c.jpg>',
                'ch4'       => '<img src=storage/questions/16_d.jpg>',
                'ch5'       => '<img src=storage/questions/16_e.jpg>',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 17,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/17_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/17_a.jpg>',
                'ch2'       => '<img src=storage/questions/17_b.jpg>',
                'ch3'       => '<img src=storage/questions/17_c.jpg>',
                'ch4'       => '<img src=storage/questions/17_d.jpg>',
                'ch5'       => '<img src=storage/questions/17_e.jpg>',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 18,
                'format'=> 'photo',
                'test_type' => 'Verbal',
                'question'  => '<img src=storage/questions/18_q.jpg>',
                'answer'    => 'ch2',
                'ch1'       => '<img src=storage/questions/18_a.jpg>',
                'ch2'       => '<img src=storage/questions/18_b.jpg>',
                'ch3'       => '<img src=storage/questions/18_c.jpg>',
                'ch4'       => '<img src=storage/questions/18_d.jpg>',
                'ch5'       => '<img src=storage/questions/18_e.jpg>',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 19,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/19_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/19_a.jpg>',
                'ch2'       => '<img src=storage/questions/19_b.jpg>',
                'ch3'       => '<img src=storage/questions/19_c.jpg>',
                'ch4'       => '<img src=storage/questions/19_d.jpg>',
                'ch5'       => '<img src=storage/questions/19_e.jpg>',
                'qtype'     => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 20,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => '<b>Increase</b> is to <b>reveal</b> as <b>decrease</b> is to ----',
                'answer'    => 'ch4',
                'ch1'       => 'reduce',
                'ch2'       => 'concede',
                'ch3'       => 'refuse',
                'ch4'       => 'conceal',
                'ch5'       => 'disclose',
                'qtype'     => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'        => 21,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'Robert buys 14 cans of dog food every week for his dogs, who each eat one can a day. If Robert has twice as many cats as dogs, how many cats does he have?',
                'answer'    => 'ch2',
                'ch1'       => '2',
                'ch2'       => '4',
                'ch3'       => '6',
                'ch4'       => '7',
                'ch5'       => '8',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 22,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/22_q.jpg>',
                'answer'    => 'ch2',
                'ch1'       => '<img src=storage/questions/22_a.jpg>',
                'ch2'       => '<img src=storage/questions/22_b.jpg>',
                'ch3'       => '<img src=storage/questions/22_c.jpg>',
                'ch4'       => '<img src=storage/questions/22_d.jpg>',
                'ch5'       => '<img src=storage/questions/22_e.jpg>',
                'qtype'     => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 23,
                'format'    => 'text',
                'test_type' => 'non-verbal',
                'question'  => 'What comes next in this series?    10C    8A    12E    10C    14G?',
                'answer'    => 'ch1',
                'ch1'       => '12E',
                'ch2'       => '12G',
                'ch3'       => '14E',
                'ch4'       => '16I',
                'ch5'       => '18K',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 24,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'Paul was born in 1970. Dick was born in 1972. If John is younger than Dick, then we know that ---',
                'answer'    => 'ch1',
                'ch1'       => 'Dick is younger than Paul and older than John',
                'ch2'       => 'Paul is older than Dick and younger than John',
                'ch3'       => 'Paul is younger than Dick and older than John',
                'ch4'       => 'Paul is younger than Dick and John',
                'ch5'       => 'Dick is older than Paul and younger than John',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 25,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'Whice word goes <i>most clearly</i> with: <b>peaceful    serene    tranquil</b>?',
                'answer'    => 'ch5',
                'ch1'       => 'joyous',
                'ch2'       => 'monotonous',
                'ch3'       => 'emotional',
                'ch4'       => 'sensible',
                'ch5'       => 'calm',
                'qtype'     => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 26,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/26_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/26_a.jpg>',
                'ch2'       => '<img src=storage/questions/26_b.jpg>',
                'ch3'       => '<img src=storage/questions/26_c.jpg>',
                'ch4'       => '<img src=storage/questions/26_d.jpg>',
                'ch5'       => '<img src=storage/questions/26_e.jpg>',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 27,
                'format'=> 'photo',
                'test_type' => 'Verbal',
                'question'  => '<img src=storage/questions/27_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/27_a.jpg>',
                'ch2'       => '<img src=storage/questions/27_b.jpg>',
                'ch3'       => '<img src=storage/questions/27_c.jpg>',
                'ch4'       => '<img src=storage/questions/27_d.jpg>',
                'ch5'       => '<img src=storage/questions/27_e.jpg>',
                'qtype'     => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 28,
                'format'    => 'text',
                'test_type' => 'Verbal',
                'question'  => 'The opposite of <b>discord</b> is ---',
                'answer'    => 'ch1',
                'ch1'       => 'harmony',
                'ch2'       => 'grace',
                'ch3'       => 'tradition',
                'ch4'       => 'silence',
                'ch5'       => 'friendliness',
                'qtype'     => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 29,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/29_q.jpg>',
                'answer'    => 'ch5',
                'ch1'       => '<img src=storage/questions/29_a.jpg>',
                'ch2'       => '<img src=storage/questions/29_b.jpg>',
                'ch3'       => '<img src=storage/questions/29_c.jpg>',
                'ch4'       => '<img src=storage/questions/29_d.jpg>',
                'ch5'       => '<img src=storage/questions/29_e.jpg>',
                'qtype'     => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'        => 30,
                'format'=> 'photo',
                'test_type' => 'non-verbal',
                'question'  => '<img src=storage/questions/30_q.jpg>',
                'answer'    => 'ch3',
                'ch1'       => '<img src=storage/questions/30_a.jpg>',
                'ch2'       => '<img src=storage/questions/30_b.jpg>',
                'ch3'       => '<img src=storage/questions/30_c.jpg>',
                'ch4'       => '<img src=storage/questions/30_d.jpg>',
                'ch5'       => '<img src=storage/questions/30_e.jpg>',
                'qtype'     => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/31_q.jpg>',
                'answer' => 'ch4',
                'ch1' => '<img src=storage/questions/31_a.jpg>',
                'ch2' => '<img src=storage/questions/31_b.jpg>',
                'ch3' => '<img src=storage/questions/31_c.jpg>',
                'ch4' => '<img src=storage/questions/31_d.jpg>',
                'ch5' => '<img src=storage/questions/31_e.jpg>',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 32,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/32_q.jpg>',
                'answer' => 'ch5',
                'ch1' => '<img src=storage/questions/32_a.jpg>',
                'ch2' => '<img src=storage/questions/32_b.jpg>',
                'ch3' => '<img src=storage/questions/32_c.jpg>',
                'ch4' => '<img src=storage/questions/32_d.jpg>',
                'ch5' => '<img src=storage/questions/32_e.jpg>',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 33,
                'format' => 'text',
                'test_type' => 'Verbal',
                'question' => '<b>Possible</b> is to <b>maybe</b> as <b>probable</b> is to ---',
                'answer' => 'ch5',
                'ch1' => 'gradually',
                'ch2' => 'hopefully',
                'ch3' => 'certainly',
                'ch4' => 'eventually',
                'ch5' => 'likely',
                'qtype' => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 34,
                'format' => 'text',
                'test_type' => 'non-verbal',
                'question' => 'Mr. and Mrs. DiNapoli have two sons and three daughters. When the whole family is together for dinner, they have to bring one extra chair to the table, How many chairs do they usually have around the table?',
                'answer' => 'ch3',
                'ch1' => '4',
                'ch2' => '5',
                'ch3' => '6',
                'ch4' => '7',
                'ch5' => '8',
                'qtype' => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 35,
                'format' => 'text',
                'test_type' => 'Verbal',
                'question' => 'The opposite of <b>moderate</b> is ----',
                'answer' => 'ch5',
                'ch1' => 'sudden',
                'ch2' => 'swift',
                'ch3' => 'treacherous',
                'ch4' => 'violent',
                'ch5' => 'extreme',
                'qtype' => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 36,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/36_q.jpg>',
                'answer' => 'ch4',
                'ch1' => '<img src=storage/questions/36_a.jpg>',
                'ch2' => '<img src=storage/questions/36_b.jpg>',
                'ch3' => '<img src=storage/questions/36_c.jpg>',
                'ch4' => '<img src=storage/questions/36_d.jpg>',
                'ch5' => '<img src=storage/questions/36_e.jpg>',
                'qtype' => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 37,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/37_q.jpg>',
                'answer' => 'ch4',
                'ch1' => '<img src=storage/questions/37_a.jpg>',
                'ch2' => '<img src=storage/questions/37_b.jpg>',
                'ch3' => '<img src=storage/questions/37_c.jpg>',
                'ch4' => '<img src=storage/questions/37_d.jpg>',
                'ch5' => '<img src=storage/questions/37_e.jpg>',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 38,
                'format' => 'text',
                'test_type' => 'Verbal',
                'question' => 'Every country must have ----',
                'answer' => 'ch3',
                'ch1' => 'coasts',
                'ch2' => 'a president',
                'ch3' => 'boundaries',
                'ch4' => 'a navy',
                'ch5' => 'a flag',
                'qtype' => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 39,
                'format' => 'text',
                'test_type' => 'non-verbal',
                'question' => 'What number is missing from this seires?    4    8    6    12    10    ?    18    36',
                'answer' => 'ch4',
                'ch1' => '8',
                'ch2' => '14',
                'ch3' => '16',
                'ch4' => '20',
                'ch5' => '24',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 40,
                'format' => 'text',
                'test_type' => 'Verbal',
                'question' => 'Assume that ---- <br> All <b>A</b>s are <b>C</b>s.<br>Some <b>D</b>s are <b>C</b>s. No <b>B</b>s. are <b>C</b>s.',
                'answer' => 'ch2',
                'ch1' => 'no <b>A</b>s are <b>D</b>s',
                'ch2' => 'no <b>A</b>s are <b>B</b>s',
                'ch3' => 'some <b>B</b>s are <b>D</b>s',
                'ch4' => 'some <b>A</b>s are both <b>C</b>s and <b>D</b>s',
                'ch5' => 'no <b>D</b>s are <b>B</b>s',
                'qtype' => 'Verbal Comprehension',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 41,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/41_q.jpg>',
                'answer' => 'ch5',
                'ch1' => '<img src=storage/questions/41_a.jpg>',
                'ch2' => '<img src=storage/questions/41_b.jpg>',
                'ch3' => '<img src=storage/questions/41_c.jpg>',
                'ch4' => '<img src=storage/questions/41_d.jpg>',
                'ch5' => '<img src=storage/questions/41_e.jpg>',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 42,
                'format' => '3',
                'test_type' => 'Verbal',
                'question' => '<img src=storage/questions/42_q.jpg>',
                'answer' => 'ch2',
                'ch1' => '<img src=storage/questions/42_a.jpg>',
                'ch2' => '<img src=storage/questions/42_b.jpg>',
                'ch3' => '<img src=storage/questions/42_c.jpg>',
                'ch4' => '<img src=storage/questions/42_d.jpg>',
                'ch5' => '<img src=storage/questions/42_e.jpg>',
                'qtype' => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 43,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/43_q.jpg>',
                'answer' => 'ch5',
                'ch1' => '<img src=storage/questions/43_b.jpg>',
                'ch2' => '<img src=storage/questions/43_c.JPG>',
                'ch3' => '<img src=storage/questions/43_d.jpg>',
                'ch4' => '<img src=storage/questions/43_e.JPG>',
                'ch5' => '<img src=storage/questions/43_a.jpg>',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 44,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/44_q.jpg>',
                'answer' => 'ch4',
                'ch1' => '<img src=storage/questions/44_a.jpg>',
                'ch2' => '<img src=storage/questions/44_b.jpg>',
                'ch3' => '<img src=storage/questions/44_c.jpg>',
                'ch4' => 'ch4',
                'ch5' => '<img src=storage/questions/44_e.jpg>',
                'qtype' => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 45,
                'format' => 'text',
                'test_type' => 'Verbal',
                'question' => 'Whice word goes <i>most clearly</i> with: <b>forward    sideways    down</b>?',
                'answer' => 'ch2',
                'ch1' => 'top',
                'ch2' => 'up',
                'ch3' => 'above',
                'ch4' => 'over',
                'ch5' => 'beyond',
                'qtype' => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 46,
                'format' => 'text',
                'test_type' => 'non-verbal',
                'question' => 'What number is equal to one-third of the difference between the squares of ten and eight?',
                'answer' => 'ch3',
                'ch1' => '3',
                'ch2' => '6',
                'ch3' => '12',
                'ch4' => '18',
                'ch5' => '36',
                'qtype' => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 47,
                'format' => 'text',
                'test_type' => 'non-verbal',
                'question' => 'What letter comes next in this series?    H    I    K    L    N    O    ?',
                'answer' => 'ch3',
                'ch1' => 'M',
                'ch2' => 'P',
                'ch3' => 'Q',
                'ch4' => 'R',
                'ch5' => 'S',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 48,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/48_q.jpg>',
                'answer' => 'ch5',
                'ch1' => '<img src=storage/questions/48_b.jpg>',
                'ch2' => '<img src=storage/questions/48_c.JPG>',
                'ch3' => '<img src=storage/questions/48_d.jpg>',
                'ch4' => '<img src=storage/questions/48_e.jpg>',
                'ch5' => '<img src=storage/questions/48_a.JPG>',
                'qtype' => 'Figural Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 49,
                'format' => '3',
                'test_type' => 'non-verbal',
                'question' => '<img src=storage/questions/49_q.JPG>',
                'answer' => 'ch3',
                'ch1' => '<img src=storage/questions/49_a.JPG>',
                'ch2' => '<img src=storage/questions/49_b.jpg>',
                'ch3' => '<img src=storage/questions/49_c.jpg>',
                'ch4' => '<img src=storage/questions/49_d.JPG>',
                'ch5' => '<img src=storage/questions/49_e.JPG>',
                'qtype' => 'Quantitative Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 50,
                'format' => 'text',
                'test_type' => 'Verbal',
                'question' => '<b>Electricity</b> is to <b>light bulb</b> as ----',
                'answer' => 'ch4',
                'ch1' => 'furnace is to heat',
                'ch2' => 'steam is to radiator',
                'ch3' => 'water is to dam',
                'ch4' => 'fuel is to engine',
                'ch5' => 'smoke is to fine',
                'qtype' => 'Verbal Reasoning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
        'id' => 51,
        'format' => 3,
        'test_type' => 'non-verbal',
        'question' => '<img src=storage/questions/51_q.JPG>',
        'answer' => 'ch2',
        'ch1' => '<img src=storage/questions/51_a.JPG>',
        'ch2' => 'ch2',
        'ch3' => '<img src=storage/questions/51_c.JPG>',
        'ch4' => '<img src=storage/questions/51_d.jpg>',
        'ch5' => '<img src=storage/questions/51_e.JPG>',
        'qtype' => 'Quantitative Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 52,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/52_q.jpg>',
        'answer' => 'ch3',
        'ch1' => '<img src=storage/questions/52_a.jpg>',
        'ch2' => '<img src=storage/questions/52_b.jpg>',
        'ch3' => '<img src=storage/questions/52_c.JPG>',
        'ch4' => '<img src=storage/questions/52_d.jpg>',
        'ch5' => '<img src=storage/questions/52_e.JPG>',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 53,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'There can be no message if there is no ----',
        'answer' => 'ch4',
        'ch1' => 'word',
        'ch2' => 'note',
        'ch3' => 'messenger',
        'ch4' => 'thought',
        'ch5' => 'pencil',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 54,
        'format' => 3,
        'test_type' => 'non-verbal',
        'question' => '<img src=storage/questions/54_q.jpg>',
        'answer' => 'ch1',
        'ch1' => '<img src=storage/questions/54_a.jpg>',
        'ch2' => '<img src=storage/questions/54_b.jpg>',
        'ch3' => '<img src=storage/questions/54_c.jpg>',
        'ch4' => '<img src=storage/questions/54_d.JPG>',
        'ch5' => '<img src=storage/questions/54_e.JPG>',
        'qtype' => 'Figural Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 55,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'Choose the words that <i>best</i> complete this sentence: <br> The evidence against him was ________ so the charge were _________',
        'answer' => 'ch5',
        'ch1' => 'convincing ---- dropped',
        'ch2' => 'feeble ---- extended',
        'ch3' => 'overwhelming ---- reduced',
        'ch4' => 'damaging ---- withdrawn',
        'ch5' => 'unsupported ---- dismissed',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 56,
        'format' => 3,
        'test_type' => 'non-verbal',
        'question' => '<img src=storage/questions/55_q.JPG>',
        'answer' => 'ch2',
        'ch1' => '<img src=storage/questions/55_a.JPG>',
        'ch2' => '<img src=storage/questions/55_b.JPG>',
        'ch3' => '<img src=storage/questions/55_c.JPG>',
        'ch4' => '<img src=storage/questions/55_d.JPG>',
        'ch5' => '<img src=storage/questions/55_e.JPG>',
        'qtype' => 'Figural Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 57,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'The opposite of <b>scarcity</b> is ----',
        'answer' => 'ch4',
        'ch1' => 'necessity',
        'ch2' => 'bonus',
        'ch3' => 'privilage',
        'ch4' => 'abundance',
        'ch5' => 'expansion',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 58,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'In a foreign language <b>tana dona meka</b> means <b>very cold water, tana neta</b> means <b>hot water,</b> and <b>dona bela</b> means <b>very good.</b> Whice word means <b>cold</b>?',
        'answer' => 'ch5',
        'ch1' => 'dona',
        'ch2' => 'neta',
        'ch3' => 'tana',
        'ch4' => 'bela',
        'ch5' => 'meka',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 59,
        'format' => 3,
        'test_type' => 'non-verbal',
        'question' => '<img src=storage/questions/59_q.JPG>',
        'answer' => 'ch4',
        'ch1' => '<img src=storage/questions/59_a.JPG>',
        'ch2' => '<img src=storage/questions/59_b.JPG>',
        'ch3' => '<img src=storage/questions/59_c.JPG>',
        'ch4' => '<img src=storage/questions/59_d.jpg>',
        'ch5' => '<img src=storage/questions/59_e.jpg>',
        'qtype' => 'Figural Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 60,
        'format' => 1,
        'test_type' => 'non-verbal',
        'question' => 'What number comes next in this series?   5    11    16    20    23    ?',
        'answer' => 'ch2',
        'ch1' => '24',
        'ch2' => '25',
        'ch3' => '27',
        'ch4' => '28',
        'ch5' => '29',
        'qtype' => 'Quantitative Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],

    [
        'id' => 61,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'Which word does <i>not</i> go with the other four?',
        'answer' => 'ch5',
        'ch1' => 'dangerous',
        'ch2' => 'risky',
        'ch3' => 'hazardous',
        'ch4' => 'unsafe',
        'ch5' => 'frightened',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 62,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/62_q.JPG>',
        'answer' => 'ch2',
        'ch1' => '<img src=storage/questions/62_a.JPG>',
        'ch2' => '<img src=storage/questions/62_b.JPG>',
        'ch3' => '<img src=storage/questions/62_c.JPG>',
        'ch4' => '<img src=storage/questions/62_d.JPG>',
        'ch5' => '<img src=storage/questions/62_e.JPG>',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 63,
        'format' => 3,
        'test_type' => 'non-verbal',
        'question' => '<img src=storage/questions/63_q.JPG>',
        'answer' => 'ch2',
        'ch1' => '<img src=storage/questions/63_a.JPG>',
        'ch2' => '<img src=storage/questions/63_b.jpg>',
        'ch3' => '<img src=storage/questions/63_c.JPG>',
        'ch4' => '<img src=storage/questions/63_d.JPG>',
        'ch5' => '<img src=storage/questions/63_e.JPG>',
        'qtype' => 'Figural Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 64,
        'format' => 3,
        'test_type' => 'non-verbal',
        'question' => '<img src=storage/questions/64_q.JPG>',
        'answer' => 'ch3',
        'ch1' => '<img src=storage/questions/64_a.JPG>',
        'ch2' => '<img src=storage/questions/64_b.JPG>',
        'ch3' => '<img src=storage/questions/64_c.jpg>',
        'ch4' => '<img src=storage/questions/64_d.jpg>',
        'ch5' => '<img src=storage/questions/64_e.JPG>',
        'qtype' => 'Quantitative Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 65,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'A cloud is always ----',
        'answer' => 'ch1',
        'ch1' => 'humid',
        'ch2' => 'fluffy',
        'ch3' => 'white',
        'ch4' => 'big',
        'ch5' => 'high',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 66,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/66_q.JPG>',
        'answer' => 'ch4',
        'ch1' => '<img src=storage/questions/66_a.JPG>',
        'ch2' => '<img src=storage/questions/66_b.JPG>',
        'ch3' => '<img src=storage/questions/66_c.JPG>',
        'ch4' => '<img src=storage/questions/66_d.JPG>',
        'ch5' => '<img src=storage/questions/66_e.jpg>',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 67,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/67_q.jpg>',
        'answer' => 'ch5',
        'ch1' => '<img src=storage/questions/67_a.JPG>',
        'ch2' => '<img src=storage/questions/67_b.JPG>',
        'ch3' => '<img src=storage/questions/67_c.JPG>',
        'ch4' => '<img src=storage/questions/67_d.jpg>',
        'ch5' => '<img src=storage/questions/67_e.jpg>',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 68,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/68_q.JPG>',
        'answer' => 'ch5',
        'ch1' => '<img src=storage/questions/68_a.JPG>',
        'ch2' => '<img src=storage/questions/68_b.JPG>',
        'ch3' => '<img src=storage/questions/68_c.JPG>',
        'ch4' => '<img src=storage/questions/68_d.jpg>',
        'ch5' => '<img src=storage/questions/68_e.jpg>',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 69,
        'format' => 3,
        'test_type' => 'non-verbal',
        'question' => '<img src=storage/questions/69_q.jpg>',
        'answer' => 'ch3',
        'ch1' => '<img src=storage/questions/69_a.JPG>',
        'ch2' => '<img src=storage/questions/69_b.jpg>',
        'ch3' => '<img src=storage/questions/69_c.JPG>',
        'ch4' => '<img src=storage/questions/69_d.JPG>',
        'ch5' => '<img src=storage/questions/69_e.JPG>',
        'qtype' => 'Quantitative Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 70,
        'format' => 3,
        'test_type' => 'Verbal',
        'question' => '<img src=storage/questions/70_q.jpg>',
        'answer' => 'ch1',
        'ch1' => '<img src=storage/questions/70_a.jpg>',
        'ch2' => '<img src=storage/questions/70_b.jpg>',
        'ch3' => '<img src=storage/questions/70_c.jpg>',
        'ch4' => '<img src=storage/questions/70_d.jpg>',
        'ch5' => '<img src=storage/questions/70_e.jpg>',
        'qtype' => 'Verbal Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 71,
        'format' => 1,
        'test_type' => 'non-verbal',
        'question' => 'what number divided by three is equal to ten plus two?',
        'answer' => 'ch5',
        'ch1' => '12',
        'ch2' => '13',
        'ch3' => '24',
        'ch4' => '30',
        'ch5' => '36',
        'qtype' => 'Quantitative Reasoning',
           'created_at' => now(),
    'updated_at' => now(),
    ],
    [
        'id' => 72,
        'format' => 1,
        'test_type' => 'Verbal',
        'question' => 'Choose the words that <i>best</i> complete this sentence: <br> Although Jamie s grades were _________, her parents were ________',
        'answer' => 'acceptable ---- disappointed',
        'ch1' => 'excellent ---- delighted',
        'ch2' => 'terrible ---- furious',
        'ch3' => 'poor ---- dissatisfied',
        'ch4' => 'acceptable ---- disappointed',
        'ch5' => 'superior ---- interested',
        'qtype' => 'Verbal Comprehension',
           'created_at' => now(),
    'updated_at' => now(),

    ],


]);
    }
}
