<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ScaledscoreSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('scaledscores')->insert([
            ['id'=>1,'raw_score_t'=>72,'scaled_score_t'=>825,'raw_score_v'=>36,'scaled_score_v'=>808,'raw_score_nv'=>36,'scaled_score_nv'=>793],
            ['id'=>2,'raw_score_t'=>71,'scaled_score_t'=>802,'raw_score_v'=>35,'scaled_score_v'=>784,'raw_score_nv'=>35,'scaled_score_nv'=>770],
            ['id'=>3,'raw_score_t'=>70,'scaled_score_t'=>777,'raw_score_v'=>34,'scaled_score_v'=>758,'raw_score_nv'=>34,'scaled_score_nv'=>744],
            ['id'=>4,'raw_score_t'=>69,'scaled_score_t'=>762,'raw_score_v'=>33,'scaled_score_v'=>742,'raw_score_nv'=>34,'scaled_score_nv'=>728],
            ['id'=>5,'raw_score_t'=>68,'scaled_score_t'=>751,'raw_score_v'=>32,'scaled_score_v'=>731,'raw_score_nv'=>32,'scaled_score_nv'=>716],
            ['id'=>6,'raw_score_t'=>67,'scaled_score_t'=>743,'raw_score_v'=>31,'scaled_score_v'=>721,'raw_score_nv'=>31,'scaled_score_nv'=>706],
            ['id'=>7,'raw_score_t'=>66,'scaled_score_t'=>735,'raw_score_v'=>30,'scaled_score_v'=>713,'raw_score_nv'=>30,'scaled_score_nv'=>698],
            ['id'=>8,'raw_score_t'=>65,'scaled_score_t'=>729,'raw_score_v'=>29,'scaled_score_v'=>706,'raw_score_nv'=>29,'scaled_score_nv'=>691],
            ['id'=>9,'raw_score_t'=>64,'scaled_score_t'=>724,'raw_score_v'=>28,'scaled_score_v'=>699,'raw_score_nv'=>28,'scaled_score_nv'=>684],
            ['id'=>10,'raw_score_t'=>63,'scaled_score_t'=>719,'raw_score_v'=>27,'scaled_score_v'=>693,'raw_score_nv'=>27,'scaled_score_nv'=>678],
            ['id'=>11,'raw_score_t'=>62,'scaled_score_t'=>714,'raw_score_v'=>26,'scaled_score_v'=>688,'raw_score_nv'=>26,'scaled_score_nv'=>673],
            ['id'=>12,'raw_score_t'=>61,'scaled_score_t'=>710,'raw_score_v'=>25,'scaled_score_v'=>682,'raw_score_nv'=>25,'scaled_score_nv'=>667],
            ['id'=>13,'raw_score_t'=>60,'scaled_score_t'=>706,'raw_score_v'=>24,'scaled_score_v'=>677,'raw_score_nv'=>24,'scaled_score_nv'=>662],
            ['id'=>14,'raw_score_t'=>59,'scaled_score_t'=>702,'raw_score_v'=>23,'scaled_score_v'=>672,'raw_score_nv'=>23,'scaled_score_nv'=>657],
            ['id'=>15,'raw_score_t'=>58,'scaled_score_t'=>698,'raw_score_v'=>22,'scaled_score_v'=>668,'raw_score_nv'=>22,'scaled_score_nv'=>653],
            ['id'=>16,'raw_score_t'=>57,'scaled_score_t'=>695,'raw_score_v'=>21,'scaled_score_v'=>663,'raw_score_nv'=>21,'scaled_score_nv'=>648],
            ['id'=>17,'raw_score_t'=>56,'scaled_score_t'=>692,'raw_score_v'=>20,'scaled_score_v'=>658,'raw_score_nv'=>20,'scaled_score_nv'=>643],
            ['id'=>18,'raw_score_t'=>55,'scaled_score_t'=>689,'raw_score_v'=>19,'scaled_score_v'=>654,'raw_score_nv'=>19,'scaled_score_nv'=>639],
            ['id'=>19,'raw_score_t'=>54,'scaled_score_t'=>686,'raw_score_v'=>18,'scaled_score_v'=>649,'raw_score_nv'=>18,'scaled_score_nv'=>634],
            ['id'=>20,'raw_score_t'=>53,'scaled_score_t'=>683,'raw_score_v'=>17,'scaled_score_v'=>645,'raw_score_nv'=>17,'scaled_score_nv'=>630],
            ['id'=>21,'raw_score_t'=>52,'scaled_score_t'=>680,'raw_score_v'=>16,'scaled_score_v'=>641,'raw_score_nv'=>16,'scaled_score_nv'=>625],
            ['id'=>22,'raw_score_t'=>51,'scaled_score_t'=>678,'raw_score_v'=>15,'scaled_score_v'=>636,'raw_score_nv'=>15,'scaled_score_nv'=>621],
            ['id'=>23,'raw_score_t'=>50,'scaled_score_t'=>675,'raw_score_v'=>14,'scaled_score_v'=>632,'raw_score_nv'=>14,'scaled_score_nv'=>616],
            ['id'=>24,'raw_score_t'=>49,'scaled_score_t'=>672,'raw_score_v'=>13,'scaled_score_v'=>627,'raw_score_nv'=>13,'scaled_score_nv'=>611],
            ['id'=>25,'raw_score_t'=>48,'scaled_score_t'=>670,'raw_score_v'=>12,'scaled_score_v'=>622,'raw_score_nv'=>12,'scaled_score_nv'=>606],
            ['id'=>26,'raw_score_t'=>47,'scaled_score_t'=>667,'raw_score_v'=>11,'scaled_score_v'=>617,'raw_score_nv'=>11,'scaled_score_nv'=>601],
            ['id'=>27,'raw_score_t'=>46,'scaled_score_t'=>665,'raw_score_v'=>10,'scaled_score_v'=>612,'raw_score_nv'=>10,'scaled_score_nv'=>596],
            ['id'=>28,'raw_score_t'=>45,'scaled_score_t'=>663,'raw_score_v'=>9,'scaled_score_v'=>606,'raw_score_nv'=>9,'scaled_score_nv'=>590],
            ['id'=>29,'raw_score_t'=>44,'scaled_score_t'=>660,'raw_score_v'=>8,'scaled_score_v'=>600,'raw_score_nv'=>8,'scaled_score_nv'=>584],
            ['id'=>30,'raw_score_t'=>43,'scaled_score_t'=>658,'raw_score_v'=>7,'scaled_score_v'=>594,'raw_score_nv'=>7,'scaled_score_nv'=>577],
            ['id'=>31,'raw_score_t'=>42,'scaled_score_t'=>656,'raw_score_v'=>6,'scaled_score_v'=>587,'raw_score_nv'=>6,'scaled_score_nv'=>570],
            ['id'=>32,'raw_score_t'=>41,'scaled_score_t'=>653,'raw_score_v'=>5,'scaled_score_v'=>579,'raw_score_nv'=>5,'scaled_score_nv'=>562],
            ['id'=>33,'raw_score_t'=>40,'scaled_score_t'=>651,'raw_score_v'=>4,'scaled_score_v'=>570,'raw_score_nv'=>4,'scaled_score_nv'=>552],
            ['id'=>34,'raw_score_t'=>39,'scaled_score_t'=>649,'raw_score_v'=>3,'scaled_score_v'=>558,'raw_score_nv'=>3,'scaled_score_nv'=>540],
            ['id'=>35,'raw_score_t'=>38,'scaled_score_t'=>646,'raw_score_v'=>2,'scaled_score_v'=>542,'raw_score_nv'=>2,'scaled_score_nv'=>524],
            ['id'=>36,'raw_score_t'=>37,'scaled_score_t'=>644,'raw_score_v'=>1,'scaled_score_v'=>516,'raw_score_nv'=>1,'scaled_score_nv'=>498],
            ['id'=>37,'raw_score_t'=>36,'scaled_score_t'=>642,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>38,'raw_score_t'=>35,'scaled_score_t'=>640,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>39,'raw_score_t'=>34,'scaled_score_t'=>637,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>40,'raw_score_t'=>33,'scaled_score_t'=>635,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>41,'raw_score_t'=>32,'scaled_score_t'=>633,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>42,'raw_score_t'=>31,'scaled_score_t'=>631,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>43,'raw_score_t'=>30,'scaled_score_t'=>628,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>44,'raw_score_t'=>29,'scaled_score_t'=>626,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>45,'raw_score_t'=>28,'scaled_score_t'=>624,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>46,'raw_score_t'=>27,'scaled_score_t'=>621,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>47,'raw_score_t'=>26,'scaled_score_t'=>619,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>48,'raw_score_t'=>25,'scaled_score_t'=>617,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>49,'raw_score_t'=>24,'scaled_score_t'=>614,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>50,'raw_score_t'=>23,'scaled_score_t'=>612,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>51,'raw_score_t'=>22,'scaled_score_t'=>609,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>52,'raw_score_t'=>21,'scaled_score_t'=>606,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>53,'raw_score_t'=>20,'scaled_score_t'=>604,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>54,'raw_score_t'=>19,'scaled_score_t'=>601,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>55,'raw_score_t'=>18,'scaled_score_t'=>598,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>56,'raw_score_t'=>17,'scaled_score_t'=>565,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>57,'raw_score_t'=>16,'scaled_score_t'=>592,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>58,'raw_score_t'=>15,'scaled_score_t'=>589,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>59,'raw_score_t'=>14,'scaled_score_t'=>586,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>60,'raw_score_t'=>13,'scaled_score_t'=>582,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>61,'raw_score_t'=>12,'scaled_score_t'=>578,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>62,'raw_score_t'=>11,'scaled_score_t'=>574,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>63,'raw_score_t'=>10,'scaled_score_t'=>570,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>64,'raw_score_t'=>9,'scaled_score_t'=>566,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>65,'raw_score_t'=>8,'scaled_score_t'=>561,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>66,'raw_score_t'=>7,'scaled_score_t'=>555,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>67,'raw_score_t'=>6,'scaled_score_t'=>549,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>68,'raw_score_t'=>5,'scaled_score_t'=>542,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>69,'raw_score_t'=>4,'scaled_score_t'=>533,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>70,'raw_score_t'=>3,'scaled_score_t'=>522,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>71,'raw_score_t'=>2,'scaled_score_t'=>507,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
            ['id'=>72,'raw_score_t'=>1,'scaled_score_t'=>482,'raw_score_v'=>0,'scaled_score_v'=>0,'raw_score_nv'=>0,'scaled_score_nv'=>0],
        ]);
    }
}
