<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TblSstosai16nvSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the tbl_sstosai_16nv table with initial data.
     */
    public function run()
    {
        DB::table('tbl_sstosai_16nv')->insert([
            [
                'id' => 1,
                'sai_a' => 149,
                'month_a' => 796,
                'sai_b' => 149,
                'month_b' => 796,
                'sai_c' => 149,
                'month_c' => 796,
                'sai_d' => 149,
                'month_d' => 796
            ],
            [
                'id' => 2,
                'sai_a' => 149,
                'month_a' => 795,
                'sai_b' => 149,
                'month_b' => 795,
                'sai_c' => 149,
                'month_c' => 795,
                'sai_d' => 149,
                'month_d' => 795
            ],
            [
                'id' => 3,
                'sai_a' => 148,
                'month_a' => 794,
                'sai_b' => 148,
                'month_b' => 794,
                'sai_c' => 148,
                'month_c' => 794,
                'sai_d' => 148,
                'month_d' => 794
            ],
            [
                'id' => 4,
                'sai_a' => 148,
                'month_a' => 793,
                'sai_b' => 148,
                'month_b' => 793,
                'sai_c' => 148,
                'month_c' => 793,
                'sai_d' => 148,
                'month_d' => 793
            ],
            [
                'id' => 5,
                'sai_a' => 147,
                'month_a' => 792,
                'sai_b' => 147,
                'month_b' => 792,
                'sai_c' => 147,
                'month_c' => 792,
                'sai_d' => 147,
                'month_d' => 792
            ],
            [
                'id' => 6,
                'sai_a' => 147,
                'month_a' => 791,
                'sai_b' => 147,
                'month_b' => 791,
                'sai_c' => 147,
                'month_c' => 791,
                'sai_d' => 147,
                'month_d' => 791
            ],
            [
                'id' => 7,
                'sai_a' => 146,
                'month_a' => 790,
                'sai_b' => 146,
                'month_b' => 790,
                'sai_c' => 146,
                'month_c' => 790,
                'sai_d' => 146,
                'month_d' => 790
            ],
            [
                'id' => 8,
                'sai_a' => 146,
                'month_a' => 789,
                'sai_b' => 146,
                'month_b' => 789,
                'sai_c' => 146,
                'month_c' => 789,
                'sai_d' => 146,
                'month_d' => 789
            ],
            [
                'id' => 9,
                'sai_a' => 145,
                'month_a' => 788,
                'sai_b' => 145,
                'month_b' => 788,
                'sai_c' => 145,
                'month_c' => 788,
                'sai_d' => 145,
                'month_d' => 788
            ],
            [
                'id' => 10,
                'sai_a' => 145,
                'month_a' => 787,
                'sai_b' => 145,
                'month_b' => 787,
                'sai_c' => 145,
                'month_c' => 787,
                'sai_d' => 145,
                'month_d' => 787
            ],
            [
                'id' => 11,
                'sai_a' => 144,
                'month_a' => 786,
                'sai_b' => 144,
                'month_b' => 786,
                'sai_c' => 144,
                'month_c' => 786,
                'sai_d' => 144,
                'month_d' => 786
            ],
            [
                'id' => 12,
                'sai_a' => 144,
                'month_a' => 785,
                'sai_b' => 144,
                'month_b' => 785,
                'sai_c' => 144,
                'month_c' => 785,
                'sai_d' => 144,
                'month_d' => 785
            ],
            [
                'id' => 13,
                'sai_a' => 143,
                'month_a' => 784,
                'sai_b' => 143,
                'month_b' => 784,
                'sai_c' => 143,
                'month_c' => 784,
                'sai_d' => 143,
                'month_d' => 784
            ],
            [
                'id' => 14,
                'sai_a' => 143,
                'month_a' => 783,
                'sai_b' => 143,
                'month_b' => 783,
                'sai_c' => 143,
                'month_c' => 783,
                'sai_d' => 143,
                'month_d' => 783
            ],
            [
                'id' => 15,
                'sai_a' => 142,
                'month_a' => 782,
                'sai_b' => 142,
                'month_b' => 782,
                'sai_c' => 142,
                'month_c' => 782,
                'sai_d' => 142,
                'month_d' => 782
            ],
            [
                'id' => 16,
                'sai_a' => 142,
                'month_a' => 781,
                'sai_b' => 142,
                'month_b' => 781,
                'sai_c' => 142,
                'month_c' => 781,
                'sai_d' => 142,
                'month_d' => 781
            ],
            [
                'id' => 17,
                'sai_a' => 142,
                'month_a' => 780,
                'sai_b' => 142,
                'month_b' => 780,
                'sai_c' => 142,
                'month_c' => 780,
                'sai_d' => 142,
                'month_d' => 780
            ],
            [
                'id' => 18,
                'sai_a' => 141,
                'month_a' => 779,
                'sai_b' => 141,
                'month_b' => 779,
                'sai_c' => 141,
                'month_c' => 779,
                'sai_d' => 141,
                'month_d' => 779
            ],
            [
                'id' => 19,
                'sai_a' => 141,
                'month_a' => 778,
                'sai_b' => 141,
                'month_b' => 778,
                'sai_c' => 141,
                'month_c' => 778,
                'sai_d' => 141,
                'month_d' => 778
            ],
            [
                'id' => 20,
                'sai_a' => 140,
                'month_a' => 777,
                'sai_b' => 140,
                'month_b' => 777,
                'sai_c' => 140,
                'month_c' => 777,
                'sai_d' => 140,
                'month_d' => 777
            ],
            [
                'id' => 21,
                'sai_a' => 140,
                'month_a' => 776,
                'sai_b' => 140,
                'month_b' => 776,
                'sai_c' => 140,
                'month_c' => 776,
                'sai_d' => 140,
                'month_d' => 776
            ],
            [
                'id' => 22,
                'sai_a' => 140,
                'month_a' => 775,
                'sai_b' => 140,
                'month_b' => 775,
                'sai_c' => 140,
                'month_c' => 775,
                'sai_d' => 140,
                'month_d' => 775
            ],
            [
                'id' => 23,
                'sai_a' => 139,
                'month_a' => 774,
                'sai_b' => 139,
                'month_b' => 774,
                'sai_c' => 139,
                'month_c' => 774,
                'sai_d' => 139,
                'month_d' => 774
            ],
            [
                'id' => 24,
                'sai_a' => 139,
                'month_a' => 773,
                'sai_b' => 139,
                'month_b' => 773,
                'sai_c' => 139,
                'month_c' => 773,
                'sai_d' => 139,
                'month_d' => 773
            ],
            [
                'id' => 25,
                'sai_a' => 139,
                'month_a' => 772,
                'sai_b' => 138,
                'month_b' => 772,
                'sai_c' => 138,
                'month_c' => 772,
                'sai_d' => 138,
                'month_d' => 772
            ],
            [
                'id' => 26,
                'sai_a' => 138,
                'month_a' => 771,
                'sai_b' => 138,
                'month_b' => 771,
                'sai_c' => 138,
                'month_c' => 771,
                'sai_d' => 138,
                'month_d' => 771
            ],
            [
                'id' => 27,
                'sai_a' => 138,
                'month_a' => 770,
                'sai_b' => 138,
                'month_b' => 770,
                'sai_c' => 138,
                'month_c' => 770,
                'sai_d' => 138,
                'month_d' => 770
            ],
            [
                'id' => 28,
                'sai_a' => 137,
                'month_a' => 769,
                'sai_b' => 137,
                'month_b' => 769,
                'sai_c' => 137,
                'month_c' => 769,
                'sai_d' => 137,
                'month_d' => 769
            ],
            [
                'id' => 29,
                'sai_a' => 137,
                'month_a' => 768,
                'sai_b' => 137,
                'month_b' => 768,
                'sai_c' => 137,
                'month_c' => 768,
                'sai_d' => 137,
                'month_d' => 768
            ],
            [
                'id' => 30,
                'sai_a' => 137,
                'month_a' => 767,
                'sai_b' => 136,
                'month_b' => 767,
                'sai_c' => 136,
                'month_c' => 767,
                'sai_d' => 136,
                'month_d' => 767
            ],
            [
                'id' => 31,
                'sai_a' => 136,
                'month_a' => 766,
                'sai_b' => 136,
                'month_b' => 766,
                'sai_c' => 136,
                'month_c' => 766,
                'sai_d' => 136,
                'month_d' => 766
            ],
            [
                'id' => 32,
                'sai_a' => 136,
                'month_a' => 765,
                'sai_b' => 136,
                'month_b' => 765,
                'sai_c' => 136,
                'month_c' => 765,
                'sai_d' => 136,
                'month_d' => 765
            ],
            [
                'id' => 33,
                'sai_a' => 136,
                'month_a' => 764,
                'sai_b' => 135,
                'month_b' => 764,
                'sai_c' => 135,
                'month_c' => 764,
                'sai_d' => 135,
                'month_d' => 764
            ],
            [
                'id' => 34,
                'sai_a' => 135,
                'month_a' => 763,
                'sai_b' => 135,
                'month_b' => 763,
                'sai_c' => 135,
                'month_c' => 763,
                'sai_d' => 135,
                'month_d' => 763
            ],
            [
                'id' => 35,
                'sai_a' => 135,
                'month_a' => 762,
                'sai_b' => 134,
                'month_b' => 762,
                'sai_c' => 134,
                'month_c' => 762,
                'sai_d' => 134,
                'month_d' => 762
            ],
            [
                'id' => 36,
                'sai_a' => 134,
                'month_a' => 761,
                'sai_b' => 134,
                'month_b' => 761,
                'sai_c' => 134,
                'month_c' => 761,
                'sai_d' => 134,
                'month_d' => 761
            ],
            [
                'id' => 37,
                'sai_a' => 134,
                'month_a' => 760,
                'sai_b' => 134,
                'month_b' => 760,
                'sai_c' => 134,
                'month_c' => 760,
                'sai_d' => 134,
                'month_d' => 760
            ],
            [
                'id' => 38,
                'sai_a' => 134,
                'month_a' => 759,
                'sai_b' => 133,
                'month_b' => 759,
                'sai_c' => 133,
                'month_c' => 759,
                'sai_d' => 133,
                'month_d' => 759
            ],
            [
                'id' => 39,
                'sai_a' => 133,
                'month_a' => 758,
                'sai_b' => 133,
                'month_b' => 758,
                'sai_c' => 133,
                'month_c' => 758,
                'sai_d' => 133,
                'month_d' => 758
            ],
            [
                'id' => 40,
                'sai_a' => 133,
                'month_a' => 757,
                'sai_b' => 133,
                'month_b' => 757,
                'sai_c' => 133,
                'month_c' => 757,
                'sai_d' => 133,
                'month_d' => 757
            ],
            [
                'id' => 41,
                'sai_a' => 133,
                'month_a' => 756,
                'sai_b' => 132,
                'month_b' => 756,
                'sai_c' => 132,
                'month_c' => 756,
                'sai_d' => 132,
                'month_d' => 756
            ],
            [
                'id' => 42,
                'sai_a' => 132,
                'month_a' => 755,
                'sai_b' => 132,
                'month_b' => 755,
                'sai_c' => 132,
                'month_c' => 755,
                'sai_d' => 132,
                'month_d' => 755
            ],
            [
                'id' => 43,
                'sai_a' => 132,
                'month_a' => 754,
                'sai_b' => 132,
                'month_b' => 754,
                'sai_c' => 132,
                'month_c' => 754,
                'sai_d' => 132,
                'month_d' => 754
            ],
            [
                'id' => 44,
                'sai_a' => 132,
                'month_a' => 753,
                'sai_b' => 131,
                'month_b' => 753,
                'sai_c' => 131,
                'month_c' => 753,
                'sai_d' => 131,
                'month_d' => 753
            ],
            [
                'id' => 45,
                'sai_a' => 131,
                'month_a' => 752,
                'sai_b' => 131,
                'month_b' => 752,
                'sai_c' => 131,
                'month_c' => 752,
                'sai_d' => 131,
                'month_d' => 752
            ],
            [
                'id' => 46,
                'sai_a' => 131,
                'month_a' => 751,
                'sai_b' => 131,
                'month_b' => 751,
                'sai_c' => 131,
                'month_c' => 751,
                'sai_d' => 131,
                'month_d' => 751
            ],
            [
                'id' => 47,
                'sai_a' => 131,
                'month_a' => 750,
                'sai_b' => 130,
                'month_b' => 750,
                'sai_c' => 130,
                'month_c' => 750,
                'sai_d' => 130,
                'month_d' => 750
            ],
            [
                'id' => 48,
                'sai_a' => 130,
                'month_a' => 749,
                'sai_b' => 130,
                'month_b' => 749,
                'sai_c' => 130,
                'month_c' => 749,
                'sai_d' => 130,
                'month_d' => 749
            ],
            [
                'id' => 49,
                'sai_a' => 130,
                'month_a' => 748,
                'sai_b' => 130,
                'month_b' => 748,
                'sai_c' => 130,
                'month_c' => 748,
                'sai_d' => 130,
                'month_d' => 748
            ],
            [
                'id' => 50,
                'sai_a' => 130,
                'month_a' => 747,
                'sai_b' => 129,
                'month_b' => 747,
                'sai_c' => 129,
                'month_c' => 747,
                'sai_d' => 129,
                'month_d' => 747
            ],
            [
                'id' => 51,
                'sai_a' => 129,
                'month_a' => 746,
                'sai_b' => 129,
                'month_b' => 746,
                'sai_c' => 129,
                'month_c' => 746,
                'sai_d' => 129,
                'month_d' => 746
            ],
            [
                'id' => 52,
                'sai_a' => 129,
                'month_a' => 745,
                'sai_b' => 128,
                'month_b' => 745,
                'sai_c' => 128,
                'month_c' => 745,
                'sai_d' => 128,
                'month_d' => 745
            ],
            [
                'id' => 53,
                'sai_a' => 129,
                'month_a' => 744,
                'sai_b' => 128,
                'month_b' => 744,
                'sai_c' => 128,
                'month_c' => 744,
                'sai_d' => 128,
                'month_d' => 744
            ],
            [
                'id' => 54,
                'sai_a' => 128,
                'month_a' => 743,
                'sai_b' => 128,
                'month_b' => 743,
                'sai_c' => 128,
                'month_c' => 743,
                'sai_d' => 128,
                'month_d' => 743
            ],
            [
                'id' => 55,
                'sai_a' => 128,
                'month_a' => 742,
                'sai_b' => 127,
                'month_b' => 742,
                'sai_c' => 127,
                'month_c' => 742,
                'sai_d' => 127,
                'month_d' => 742
            ],
            [
                'id' => 56,
                'sai_a' => 128,
                'month_a' => 741,
                'sai_b' => 127,
                'month_b' => 741,
                'sai_c' => 127,
                'month_c' => 741,
                'sai_d' => 127,
                'month_d' => 741
            ],
            [
                'id' => 57,
                'sai_a' => 127,
                'month_a' => 740,
                'sai_b' => 127,
                'month_b' => 740,
                'sai_c' => 127,
                'month_c' => 740,
                'sai_d' => 127,
                'month_d' => 740
            ],
            [
                'id' => 58,
                'sai_a' => 127,
                'month_a' => 739,
                'sai_b' => 126,
                'month_b' => 739,
                'sai_c' => 126,
                'month_c' => 739,
                'sai_d' => 126,
                'month_d' => 739
            ],
            [
                'id' => 59,
                'sai_a' => 127,
                'month_a' => 738,
                'sai_b' => 126,
                'month_b' => 738,
                'sai_c' => 126,
                'month_c' => 738,
                'sai_d' => 126,
                'month_d' => 738
            ],
            [
                'id' => 60,
                'sai_a' => 126,
                'month_a' => 737,
                'sai_b' => 126,
                'month_b' => 737,
                'sai_c' => 126,
                'month_c' => 737,
                'sai_d' => 126,
                'month_d' => 737
            ],
            [
                'id' => 61,
                'sai_a' => 126,
                'month_a' => 736,
                'sai_b' => 125,
                'month_b' => 736,
                'sai_c' => 125,
                'month_c' => 736,
                'sai_d' => 125,
                'month_d' => 736
            ],
            [
                'id' => 62,
                'sai_a' => 126,
                'month_a' => 735,
                'sai_b' => 125,
                'month_b' => 735,
                'sai_c' => 125,
                'month_c' => 735,
                'sai_d' => 125,
                'month_d' => 735
            ],
            [
                'id' => 63,
                'sai_a' => 125,
                'month_a' => 734,
                'sai_b' => 125,
                'month_b' => 734,
                'sai_c' => 125,
                'month_c' => 734,
                'sai_d' => 125,
                'month_d' => 734
            ],
            [
                'id' => 64,
                'sai_a' => 125,
                'month_a' => 733,
                'sai_b' => 124,
                'month_b' => 733,
                'sai_c' => 124,
                'month_c' => 733,
                'sai_d' => 124,
                'month_d' => 733
            ],
            [
                'id' => 65,
                'sai_a' => 125,
                'month_a' => 732,
                'sai_b' => 124,
                'month_b' => 732,
                'sai_c' => 124,
                'month_c' => 732,
                'sai_d' => 124,
                'month_d' => 732
            ],
            [
                'id' => 66,
                'sai_a' => 124,
                'month_a' => 731,
                'sai_b' => 124,
                'month_b' => 731,
                'sai_c' => 124,
                'month_c' => 731,
                'sai_d' => 124,
                'month_d' => 731
            ],
            [
                'id' => 67,
                'sai_a' => 124,
                'month_a' => 730,
                'sai_b' => 123,
                'month_b' => 730,
                'sai_c' => 123,
                'month_c' => 730,
                'sai_d' => 123,
                'month_d' => 730
            ],
            [
                'id' => 68,
                'sai_a' => 124,
                'month_a' => 729,
                'sai_b' => 123,
                'month_b' => 729,
                'sai_c' => 123,
                'month_c' => 729,
                'sai_d' => 123,
                'month_d' => 729
            ],
            [
                'id' => 69,
                'sai_a' => 123,
                'month_a' => 728,
                'sai_b' => 123,
                'month_b' => 728,
                'sai_c' => 123,
                'month_c' => 728,
                'sai_d' => 123,
                'month_d' => 728
            ],
            [
                'id' => 70,
                'sai_a' => 123,
                'month_a' => 727,
                'sai_b' => 123,
                'month_b' => 727,
                'sai_c' => 123,
                'month_c' => 727,
                'sai_d' => 123,
                'month_d' => 727
            ],
            [
                'id' => 71,
                'sai_a' => 123,
                'month_a' => 726,
                'sai_b' => 122,
                'month_b' => 726,
                'sai_c' => 122,
                'month_c' => 726,
                'sai_d' => 122,
                'month_d' => 726
            ],
            [
                'id' => 72,
                'sai_a' => 122,
                'month_a' => 725,
                'sai_b' => 122,
                'month_b' => 725,
                'sai_c' => 122,
                'month_c' => 725,
                'sai_d' => 122,
                'month_d' => 725
            ],
            [
                'id' => 73,
                'sai_a' => 122,
                'month_a' => 724,
                'sai_b' => 122,
                'month_b' => 724,
                'sai_c' => 122,
                'month_c' => 724,
                'sai_d' => 122,
                'month_d' => 724
            ],
            [
                'id' => 74,
                'sai_a' => 122,
                'month_a' => 723,
                'sai_b' => 121,
                'month_b' => 723,
                'sai_c' => 121,
                'month_c' => 723,
                'sai_d' => 121,
                'month_d' => 723
            ],
            [
                'id' => 75,
                'sai_a' => 121,
                'month_a' => 722,
                'sai_b' => 121,
                'month_b' => 722,
                'sai_c' => 121,
                'month_c' => 722,
                'sai_d' => 121,
                'month_d' => 722
            ],
            [
                'id' => 76,
                'sai_a' => 121,
                'month_a' => 721,
                'sai_b' => 121,
                'month_b' => 721,
                'sai_c' => 121,
                'month_c' => 721,
                'sai_d' => 121,
                'month_d' => 721
            ],
            [
                'id' => 77,
                'sai_a' => 121,
                'month_a' => 720,
                'sai_b' => 120,
                'month_b' => 720,
                'sai_c' => 120,
                'month_c' => 720,
                'sai_d' => 120,
                'month_d' => 720
            ],
            [
                'id' => 78,
                'sai_a' => 120,
                'month_a' => 719,
                'sai_b' => 120,
                'month_b' => 719,
                'sai_c' => 120,
                'month_c' => 719,
                'sai_d' => 120,
                'month_d' => 719
            ],
            [
                'id' => 79,
                'sai_a' => 120,
                'month_a' => 718,
                'sai_b' => 120,
                'month_b' => 718,
                'sai_c' => 120,
                'month_c' => 718,
                'sai_d' => 120,
                'month_d' => 718
            ],
            [
                'id' => 80,
                'sai_a' => 120,
                'month_a' => 717,
                'sai_b' => 119,
                'month_b' => 717,
                'sai_c' => 119,
                'month_c' => 717,
                'sai_d' => 119,
                'month_d' => 717
            ],
            [
                'id' => 81,
                'sai_a' => 119,
                'month_a' => 716,
                'sai_b' => 119,
                'month_b' => 716,
                'sai_c' => 119,
                'month_c' => 716,
                'sai_d' => 119,
                'month_d' => 716
            ],
            [
                'id' => 82,
                'sai_a' => 119,
                'month_a' => 715,
                'sai_b' => 119,
                'month_b' => 715,
                'sai_c' => 119,
                'month_c' => 715,
                'sai_d' => 119,
                'month_d' => 715
            ],
            [
                'id' => 83,
                'sai_a' => 119,
                'month_a' => 714,
                'sai_b' => 118,
                'month_b' => 714,
                'sai_c' => 118,
                'month_c' => 714,
                'sai_d' => 118,
                'month_d' => 714
            ],
            [
                'id' => 84,
                'sai_a' => 118,
                'month_a' => 713,
                'sai_b' => 118,
                'month_b' => 713,
                'sai_c' => 118,
                'month_c' => 713,
                'sai_d' => 118,
                'month_d' => 713
            ],
            [
                'id' => 85,
                'sai_a' => 118,
                'month_a' => 712,
                'sai_b' => 118,
                'month_b' => 712,
                'sai_c' => 118,
                'month_c' => 712,
                'sai_d' => 118,
                'month_d' => 712
            ],
            [
                'id' => 86,
                'sai_a' => 118,
                'month_a' => 711,
                'sai_b' => 117,
                'month_b' => 711,
                'sai_c' => 117,
                'month_c' => 711,
                'sai_d' => 117,
                'month_d' => 711
            ],
            [
                'id' => 87,
                'sai_a' => 117,
                'month_a' => 710,
                'sai_b' => 117,
                'month_b' => 710,
                'sai_c' => 117,
                'month_c' => 710,
                'sai_d' => 117,
                'month_d' => 710
            ],
            [
                'id' => 88,
                'sai_a' => 117,
                'month_a' => 709,
                'sai_b' => 117,
                'month_b' => 709,
                'sai_c' => 117,
                'month_c' => 709,
                'sai_d' => 117,
                'month_d' => 709
            ],
            [
                'id' => 89,
                'sai_a' => 117,
                'month_a' => 708,
                'sai_b' => 116,
                'month_b' => 708,
                'sai_c' => 116,
                'month_c' => 708,
                'sai_d' => 116,
                'month_d' => 708
            ],
            [
                'id' => 90,
                'sai_a' => 116,
                'month_a' => 707,
                'sai_b' => 116,
                'month_b' => 707,
                'sai_c' => 116,
                'month_c' => 707,
                'sai_d' => 116,
                'month_d' => 707
            ],
            [
                'id' => 91,
                'sai_a' => 116,
                'month_a' => 706,
                'sai_b' => 116,
                'month_b' => 706,
                'sai_c' => 116,
                'month_c' => 706,
                'sai_d' => 116,
                'month_d' => 706
            ],
            [
                'id' => 92,
                'sai_a' => 116,
                'month_a' => 705,
                'sai_b' => 115,
                'month_b' => 705,
                'sai_c' => 115,
                'month_c' => 705,
                'sai_d' => 115,
                'month_d' => 705
            ],
            [
                'id' => 93,
                'sai_a' => 115,
                'month_a' => 704,
                'sai_b' => 115,
                'month_b' => 704,
                'sai_c' => 115,
                'month_c' => 704,
                'sai_d' => 115,
                'month_d' => 704
            ],
            [
                'id' => 94,
                'sai_a' => 115,
                'month_a' => 703,
                'sai_b' => 115,
                'month_b' => 703,
                'sai_c' => 115,
                'month_c' => 703,
                'sai_d' => 115,
                'month_d' => 703
            ],
            [
                'id' => 95,
                'sai_a' => 115,
                'month_a' => 702,
                'sai_b' => 115,
                'month_b' => 702,
                'sai_c' => 115,
                'month_c' => 702,
                'sai_d' => 115,
                'month_d' => 702
            ],
            [
                'id' => 96,
                'sai_a' => 115,
                'month_a' => 701,
                'sai_b' => 114,
                'month_b' => 701,
                'sai_c' => 114,
                'month_c' => 701,
                'sai_d' => 114,
                'month_d' => 701
            ],
            [
                'id' => 97,
                'sai_a' => 114,
                'month_a' => 700,
                'sai_b' => 114,
                'month_b' => 700,
                'sai_c' => 114,
                'month_c' => 700,
                'sai_d' => 114,
                'month_d' => 700
            ],
            [
                'id' => 98,
                'sai_a' => 114,
                'month_a' => 699,
                'sai_b' => 114,
                'month_b' => 699,
                'sai_c' => 114,
                'month_c' => 699,
                'sai_d' => 114,
                'month_d' => 699
            ],
            [
                'id' => 99,
                'sai_a' => 114,
                'month_a' => 698,
                'sai_b' => 113,
                'month_b' => 698,
                'sai_c' => 113,
                'month_c' => 698,
                'sai_d' => 113,
                'month_d' => 698
            ],
            [
                'id' => 100,
                'sai_a' => 113,
                'month_a' => 697,
                'sai_b' => 113,
                'month_b' => 697,
                'sai_c' => 113,
                'month_c' => 697,
                'sai_d' => 113,
                'month_d' => 697
            ]
        ]);

        DB::table('tbl_sstosai_16nv')->insert([
            [
                'id' => 101,
                'sai_a' => 113,
                'month_a' => 696,
                'sai_b' => 113,
                'month_b' => 696,
                'sai_c' => 113,
                'month_c' => 696,
                'sai_d' => 113,
                'month_d' => 696
            ],
            [
                'id' => 102,
                'sai_a' => 113,
                'month_a' => 695,
                'sai_b' => 112,
                'month_b' => 695,
                'sai_c' => 112,
                'month_c' => 695,
                'sai_d' => 112,
                'month_d' => 695
            ],
            [
                'id' => 103,
                'sai_a' => 112,
                'month_a' => 694,
                'sai_b' => 112,
                'month_b' => 694,
                'sai_c' => 112,
                'month_c' => 694,
                'sai_d' => 112,
                'month_d' => 694
            ],
            [
                'id' => 104,
                'sai_a' => 112,
                'month_a' => 693,
                'sai_b' => 112,
                'month_b' => 693,
                'sai_c' => 112,
                'month_c' => 693,
                'sai_d' => 112,
                'month_d' => 693
            ],
            [
                'id' => 105,
                'sai_a' => 112,
                'month_a' => 692,
                'sai_b' => 111,
                'month_b' => 692,
                'sai_c' => 111,
                'month_c' => 692,
                'sai_d' => 111,
                'month_d' => 692
            ],
            [
                'id' => 106,
                'sai_a' => 111,
                'month_a' => 691,
                'sai_b' => 111,
                'month_b' => 691,
                'sai_c' => 111,
                'month_c' => 691,
                'sai_d' => 111,
                'month_d' => 691
            ],
            [
                'id' => 107,
                'sai_a' => 111,
                'month_a' => 690,
                'sai_b' => 111,
                'month_b' => 690,
                'sai_c' => 111,
                'month_c' => 690,
                'sai_d' => 111,
                'month_d' => 690
            ],
            [
                'id' => 108,
                'sai_a' => 111,
                'month_a' => 689,
                'sai_b' => 110,
                'month_b' => 689,
                'sai_c' => 110,
                'month_c' => 689,
                'sai_d' => 110,
                'month_d' => 689
            ],
            [
                'id' => 109,
                'sai_a' => 110,
                'month_a' => 688,
                'sai_b' => 110,
                'month_b' => 688,
                'sai_c' => 110,
                'month_c' => 688,
                'sai_d' => 110,
                'month_d' => 688
            ],
            [
                'id' => 110,
                'sai_a' => 110,
                'month_a' => 687,
                'sai_b' => 110,
                'month_b' => 687,
                'sai_c' => 110,
                'month_c' => 687,
                'sai_d' => 110,
                'month_d' => 687
            ],
            [
                'id' => 111,
                'sai_a' => 110,
                'month_a' => 686,
                'sai_b' => 109,
                'month_b' => 686,
                'sai_c' => 109,
                'month_c' => 686,
                'sai_d' => 109,
                'month_d' => 686
            ],
            [
                'id' => 112,
                'sai_a' => 109,
                'month_a' => 685,
                'sai_b' => 109,
                'month_b' => 685,
                'sai_c' => 109,
                'month_c' => 685,
                'sai_d' => 109,
                'month_d' => 685
            ],
            [
                'id' => 113,
                'sai_a' => 109,
                'month_a' => 684,
                'sai_b' => 109,
                'month_b' => 684,
                'sai_c' => 109,
                'month_c' => 684,
                'sai_d' => 109,
                'month_d' => 684
            ],
            [
                'id' => 114,
                'sai_a' => 109,
                'month_a' => 683,
                'sai_b' => 108,
                'month_b' => 683,
                'sai_c' => 108,
                'month_c' => 683,
                'sai_d' => 108,
                'month_d' => 683
            ],
            [
                'id' => 115,
                'sai_a' => 108,
                'month_a' => 682,
                'sai_b' => 108,
                'month_b' => 682,
                'sai_c' => 108,
                'month_c' => 682,
                'sai_d' => 108,
                'month_d' => 682
            ],
            [
                'id' => 116,
                'sai_a' => 108,
                'month_a' => 681,
                'sai_b' => 108,
                'month_b' => 681,
                'sai_c' => 108,
                'month_c' => 681,
                'sai_d' => 108,
                'month_d' => 681
            ],
            [
                'id' => 117,
                'sai_a' => 108,
                'month_a' => 680,
                'sai_b' => 107,
                'month_b' => 680,
                'sai_c' => 107,
                'month_c' => 680,
                'sai_d' => 107,
                'month_d' => 680
            ],
            [
                'id' => 118,
                'sai_a' => 107,
                'month_a' => 679,
                'sai_b' => 107,
                'month_b' => 679,
                'sai_c' => 107,
                'month_c' => 679,
                'sai_d' => 107,
                'month_d' => 679
            ],
            [
                'id' => 119,
                'sai_a' => 107,
                'month_a' => 678,
                'sai_b' => 107,
                'month_b' => 678,
                'sai_c' => 107,
                'month_c' => 678,
                'sai_d' => 107,
                'month_d' => 678
            ],
            [
                'id' => 120,
                'sai_a' => 107,
                'month_a' => 677,
                'sai_b' => 106,
                'month_b' => 677,
                'sai_c' => 106,
                'month_c' => 677,
                'sai_d' => 106,
                'month_d' => 677
            ],
            [
                'id' => 121,
                'sai_a' => 106,
                'month_a' => 676,
                'sai_b' => 106,
                'month_b' => 676,
                'sai_c' => 106,
                'month_c' => 676,
                'sai_d' => 106,
                'month_d' => 676
            ],
            [
                'id' => 122,
                'sai_a' => 106,
                'month_a' => 675,
                'sai_b' => 106,
                'month_b' => 675,
                'sai_c' => 106,
                'month_c' => 675,
                'sai_d' => 106,
                'month_d' => 675
            ],
            [
                'id' => 123,
                'sai_a' => 106,
                'month_a' => 674,
                'sai_b' => 105,
                'month_b' => 674,
                'sai_c' => 105,
                'month_c' => 674,
                'sai_d' => 105,
                'month_d' => 674
            ],
            [
                'id' => 124,
                'sai_a' => 105,
                'month_a' => 673,
                'sai_b' => 105,
                'month_b' => 673,
                'sai_c' => 105,
                'month_c' => 673,
                'sai_d' => 105,
                'month_d' => 673
            ],
            [
                'id' => 125,
                'sai_a' => 105,
                'month_a' => 672,
                'sai_b' => 105,
                'month_b' => 672,
                'sai_c' => 105,
                'month_c' => 672,
                'sai_d' => 105,
                'month_d' => 672
            ],
            [
                'id' => 126,
                'sai_a' => 105,
                'month_a' => 671,
                'sai_b' => 105,
                'month_b' => 671,
                'sai_c' => 105,
                'month_c' => 671,
                'sai_d' => 105,
                'month_d' => 671
            ],
            [
                'id' => 127,
                'sai_a' => 104,
                'month_a' => 670,
                'sai_b' => 104,
                'month_b' => 670,
                'sai_c' => 104,
                'month_c' => 670,
                'sai_d' => 104,
                'month_d' => 670
            ],
            [
                'id' => 128,
                'sai_a' => 104,
                'month_a' => 669,
                'sai_b' => 104,
                'month_b' => 669,
                'sai_c' => 104,
                'month_c' => 669,
                'sai_d' => 104,
                'month_d' => 669
            ],
            [
                'id' => 129,
                'sai_a' => 104,
                'month_a' => 668,
                'sai_b' => 104,
                'month_b' => 668,
                'sai_c' => 104,
                'month_c' => 668,
                'sai_d' => 104,
                'month_d' => 668
            ],
            [
                'id' => 130,
                'sai_a' => 104,
                'month_a' => 667,
                'sai_b' => 103,
                'month_b' => 667,
                'sai_c' => 103,
                'month_c' => 667,
                'sai_d' => 103,
                'month_d' => 667
            ],
            [
                'id' => 131,
                'sai_a' => 103,
                'month_a' => 666,
                'sai_b' => 103,
                'month_b' => 666,
                'sai_c' => 103,
                'month_c' => 666,
                'sai_d' => 103,
                'month_d' => 666
            ],
            [
                'id' => 132,
                'sai_a' => 103,
                'month_a' => 665,
                'sai_b' => 103,
                'month_b' => 665,
                'sai_c' => 102,
                'month_c' => 665,
                'sai_d' => 102,
                'month_d' => 665
            ],
            [
                'id' => 133,
                'sai_a' => 103,
                'month_a' => 664,
                'sai_b' => 102,
                'month_b' => 664,
                'sai_c' => 102,
                'month_c' => 664,
                'sai_d' => 102,
                'month_d' => 664
            ],
            [
                'id' => 134,
                'sai_a' => 103,
                'month_a' => 663,
                'sai_b' => 102,
                'month_b' => 663,
                'sai_c' => 102,
                'month_c' => 663,
                'sai_d' => 102,
                'month_d' => 663
            ],
            [
                'id' => 135,
                'sai_a' => 102,
                'month_a' => 662,
                'sai_b' => 102,
                'month_b' => 662,
                'sai_c' => 101,
                'month_c' => 662,
                'sai_d' => 101,
                'month_d' => 662
            ],
            [
                'id' => 136,
                'sai_a' => 102,
                'month_a' => 661,
                'sai_b' => 101,
                'month_b' => 661,
                'sai_c' => 101,
                'month_c' => 661,
                'sai_d' => 101,
                'month_d' => 661
            ],
            [
                'id' => 137,
                'sai_a' => 101,
                'month_a' => 660,
                'sai_b' => 101,
                'month_b' => 660,
                'sai_c' => 101,
                'month_c' => 660,
                'sai_d' => 101,
                'month_d' => 660
            ],
            [
                'id' => 138,
                'sai_a' => 101,
                'month_a' => 659,
                'sai_b' => 101,
                'month_b' => 659,
                'sai_c' => 100,
                'month_c' => 659,
                'sai_d' => 100,
                'month_d' => 659
            ],
            [
                'id' => 139,
                'sai_a' => 101,
                'month_a' => 658,
                'sai_b' => 100,
                'month_b' => 658,
                'sai_c' => 100,
                'month_c' => 658,
                'sai_d' => 100,
                'month_d' => 658
            ],
            [
                'id' => 140,
                'sai_a' => 100,
                'month_a' => 657,
                'sai_b' => 100,
                'month_b' => 657,
                'sai_c' => 100,
                'month_c' => 657,
                'sai_d' => 100,
                'month_d' => 657
            ],
            [
                'id' => 141,
                'sai_a' => 100,
                'month_a' => 656,
                'sai_b' => 99,
                'month_b' => 656,
                'sai_c' => 99,
                'month_c' => 656,
                'sai_d' => 99,
                'month_d' => 656
            ],
            [
                'id' => 142,
                'sai_a' => 99,
                'month_a' => 655,
                'sai_b' => 99,
                'month_b' => 655,
                'sai_c' => 99,
                'month_c' => 655,
                'sai_d' => 99,
                'month_d' => 655
            ],
            [
                'id' => 143,
                'sai_a' => 99,
                'month_a' => 654,
                'sai_b' => 99,
                'month_b' => 654,
                'sai_c' => 99,
                'month_c' => 654,
                'sai_d' => 99,
                'month_d' => 654
            ],
            [
                'id' => 144,
                'sai_a' => 99,
                'month_a' => 653,
                'sai_b' => 98,
                'month_b' => 653,
                'sai_c' => 98,
                'month_c' => 653,
                'sai_d' => 98,
                'month_d' => 653
            ],
            [
                'id' => 145,
                'sai_a' => 98,
                'month_a' => 652,
                'sai_b' => 98,
                'month_b' => 652,
                'sai_c' => 98,
                'month_c' => 652,
                'sai_d' => 98,
                'month_d' => 652
            ],
            [
                'id' => 146,
                'sai_a' => 98,
                'month_a' => 651,
                'sai_b' => 98,
                'month_b' => 651,
                'sai_c' => 98,
                'month_c' => 651,
                'sai_d' => 98,
                'month_d' => 651
            ],
            [
                'id' => 147,
                'sai_a' => 98,
                'month_a' => 650,
                'sai_b' => 97,
                'month_b' => 650,
                'sai_c' => 97,
                'month_c' => 650,
                'sai_d' => 97,
                'month_d' => 650
            ],
            [
                'id' => 148,
                'sai_a' => 97,
                'month_a' => 649,
                'sai_b' => 97,
                'month_b' => 649,
                'sai_c' => 97,
                'month_c' => 649,
                'sai_d' => 97,
                'month_d' => 649
            ],
            [
                'id' => 149,
                'sai_a' => 97,
                'month_a' => 648,
                'sai_b' => 97,
                'month_b' => 648,
                'sai_c' => 96,
                'month_c' => 648,
                'sai_d' => 96,
                'month_d' => 648
            ],
            [
                'id' => 150,
                'sai_a' => 97,
                'month_a' => 647,
                'sai_b' => 96,
                'month_b' => 647,
                'sai_c' => 96,
                'month_c' => 647,
                'sai_d' => 96,
                'month_d' => 647
            ],
            [
                'id' => 151,
                'sai_a' => 96,
                'month_a' => 646,
                'sai_b' => 96,
                'month_b' => 646,
                'sai_c' => 96,
                'month_c' => 646,
                'sai_d' => 96,
                'month_d' => 646
            ],
            [
                'id' => 152,
                'sai_a' => 96,
                'month_a' => 645,
                'sai_b' => 96,
                'month_b' => 645,
                'sai_c' => 95,
                'month_c' => 645,
                'sai_d' => 95,
                'month_d' => 645
            ],
            [
                'id' => 153,
                'sai_a' => 96,
                'month_a' => 644,
                'sai_b' => 95,
                'month_b' => 644,
                'sai_c' => 95,
                'month_c' => 644,
                'sai_d' => 95,
                'month_d' => 644
            ],
            [
                'id' => 154,
                'sai_a' => 95,
                'month_a' => 643,
                'sai_b' => 95,
                'month_b' => 643,
                'sai_c' => 95,
                'month_c' => 643,
                'sai_d' => 95,
                'month_d' => 643
            ],
            [
                'id' => 155,
                'sai_a' => 95,
                'month_a' => 642,
                'sai_b' => 95,
                'month_b' => 642,
                'sai_c' => 94,
                'month_c' => 642,
                'sai_d' => 94,
                'month_d' => 642
            ],
            [
                'id' => 156,
                'sai_a' => 95,
                'month_a' => 641,
                'sai_b' => 94,
                'month_b' => 641,
                'sai_c' => 94,
                'month_c' => 641,
                'sai_d' => 94,
                'month_d' => 641
            ],
            [
                'id' => 157,
                'sai_a' => 94,
                'month_a' => 640,
                'sai_b' => 94,
                'month_b' => 640,
                'sai_c' => 94,
                'month_c' => 640,
                'sai_d' => 94,
                'month_d' => 640
            ],
            [
                'id' => 158,
                'sai_a' => 94,
                'month_a' => 639,
                'sai_b' => 94,
                'month_b' => 639,
                'sai_c' => 93,
                'month_c' => 639,
                'sai_d' => 93,
                'month_d' => 639
            ],
            [
                'id' => 159,
                'sai_a' => 94,
                'month_a' => 638,
                'sai_b' => 93,
                'month_b' => 638,
                'sai_c' => 93,
                'month_c' => 638,
                'sai_d' => 93,
                'month_d' => 638
            ],
            [
                'id' => 160,
                'sai_a' => 93,
                'month_a' => 637,
                'sai_b' => 93,
                'month_b' => 637,
                'sai_c' => 92,
                'month_c' => 637,
                'sai_d' => 92,
                'month_d' => 637
            ],
            [
                'id' => 161,
                'sai_a' => 93,
                'month_a' => 636,
                'sai_b' => 92,
                'month_b' => 636,
                'sai_c' => 92,
                'month_c' => 636,
                'sai_d' => 92,
                'month_d' => 636
            ],
            [
                'id' => 162,
                'sai_a' => 93,
                'month_a' => 635,
                'sai_b' => 92,
                'month_b' => 635,
                'sai_c' => 92,
                'month_c' => 635,
                'sai_d' => 92,
                'month_d' => 635
            ],
            [
                'id' => 163,
                'sai_a' => 92,
                'month_a' => 634,
                'sai_b' => 92,
                'month_b' => 634,
                'sai_c' => 91,
                'month_c' => 634,
                'sai_d' => 91,
                'month_d' => 634
            ],
            [
                'id' => 164,
                'sai_a' => 92,
                'month_a' => 633,
                'sai_b' => 91,
                'month_b' => 633,
                'sai_c' => 91,
                'month_c' => 633,
                'sai_d' => 91,
                'month_d' => 633
            ],
            [
                'id' => 165,
                'sai_a' => 92,
                'month_a' => 632,
                'sai_b' => 91,
                'month_b' => 632,
                'sai_c' => 91,
                'month_c' => 632,
                'sai_d' => 91,
                'month_d' => 632
            ],
            [
                'id' => 166,
                'sai_a' => 91,
                'month_a' => 631,
                'sai_b' => 91,
                'month_b' => 631,
                'sai_c' => 90,
                'month_c' => 631,
                'sai_d' => 90,
                'month_d' => 631
            ],
            [
                'id' => 167,
                'sai_a' => 91,
                'month_a' => 630,
                'sai_b' => 90,
                'month_b' => 630,
                'sai_c' => 90,
                'month_c' => 630,
                'sai_d' => 90,
                'month_d' => 630
            ],
            [
                'id' => 168,
                'sai_a' => 90,
                'month_a' => 629,
                'sai_b' => 90,
                'month_b' => 629,
                'sai_c' => 90,
                'month_c' => 629,
                'sai_d' => 90,
                'month_d' => 629
            ],
            [
                'id' => 169,
                'sai_a' => 90,
                'month_a' => 628,
                'sai_b' => 90,
                'month_b' => 628,
                'sai_c' => 89,
                'month_c' => 628,
                'sai_d' => 89,
                'month_d' => 628
            ],
            [
                'id' => 170,
                'sai_a' => 90,
                'month_a' => 627,
                'sai_b' => 89,
                'month_b' => 627,
                'sai_c' => 89,
                'month_c' => 627,
                'sai_d' => 89,
                'month_d' => 627
            ],
            [
                'id' => 171,
                'sai_a' => 89,
                'month_a' => 626,
                'sai_b' => 89,
                'month_b' => 626,
                'sai_c' => 88,
                'month_c' => 626,
                'sai_d' => 88,
                'month_d' => 626
            ],
            [
                'id' => 172,
                'sai_a' => 89,
                'month_a' => 625,
                'sai_b' => 88,
                'month_b' => 625,
                'sai_c' => 88,
                'month_c' => 625,
                'sai_d' => 88,
                'month_d' => 625
            ],
            [
                'id' => 173,
                'sai_a' => 88,
                'month_a' => 624,
                'sai_b' => 88,
                'month_b' => 624,
                'sai_c' => 88,
                'month_c' => 624,
                'sai_d' => 88,
                'month_d' => 624
            ],
            [
                'id' => 174,
                'sai_a' => 88,
                'month_a' => 623,
                'sai_b' => 88,
                'month_b' => 623,
                'sai_c' => 87,
                'month_c' => 623,
                'sai_d' => 87,
                'month_d' => 623
            ],
            [
                'id' => 175,
                'sai_a' => 88,
                'month_a' => 622,
                'sai_b' => 87,
                'month_b' => 622,
                'sai_c' => 87,
                'month_c' => 622,
                'sai_d' => 87,
                'month_d' => 622
            ],
            [
                'id' => 176,
                'sai_a' => 87,
                'month_a' => 621,
                'sai_b' => 87,
                'month_b' => 621,
                'sai_c' => 87,
                'month_c' => 621,
                'sai_d' => 87,
                'month_d' => 621
            ],
            [
                'id' => 177,
                'sai_a' => 87,
                'month_a' => 620,
                'sai_b' => 87,
                'month_b' => 620,
                'sai_c' => 86,
                'month_c' => 620,
                'sai_d' => 86,
                'month_d' => 620
            ],
            [
                'id' => 178,
                'sai_a' => 86,
                'month_a' => 619,
                'sai_b' => 86,
                'month_b' => 619,
                'sai_c' => 86,
                'month_c' => 619,
                'sai_d' => 86,
                'month_d' => 619
            ],
            [
                'id' => 179,
                'sai_a' => 86,
                'month_a' => 618,
                'sai_b' => 86,
                'month_b' => 618,
                'sai_c' => 86,
                'month_c' => 618,
                'sai_d' => 86,
                'month_d' => 618
            ],
            [
                'id' => 180,
                'sai_a' => 85,
                'month_a' => 617,
                'sai_b' => 85,
                'month_b' => 617,
                'sai_c' => 85,
                'month_c' => 617,
                'sai_d' => 85,
                'month_d' => 617
            ],
            [
                'id' => 181,
                'sai_a' => 85,
                'month_a' => 616,
                'sai_b' => 85,
                'month_b' => 616,
                'sai_c' => 85,
                'month_c' => 616,
                'sai_d' => 85,
                'month_d' => 616
            ],
            [
                'id' => 182,
                'sai_a' => 85,
                'month_a' => 615,
                'sai_b' => 85,
                'month_b' => 615,
                'sai_c' => 84,
                'month_c' => 615,
                'sai_d' => 84,
                'month_d' => 615
            ],
            [
                'id' => 183,
                'sai_a' => 84,
                'month_a' => 614,
                'sai_b' => 84,
                'month_b' => 614,
                'sai_c' => 84,
                'month_c' => 614,
                'sai_d' => 84,
                'month_d' => 614
            ],
            [
                'id' => 184,
                'sai_a' => 84,
                'month_a' => 613,
                'sai_b' => 84,
                'month_b' => 613,
                'sai_c' => 84,
                'month_c' => 613,
                'sai_d' => 84,
                'month_d' => 613
            ],
            [
                'id' => 185,
                'sai_a' => 83,
                'month_a' => 612,
                'sai_b' => 83,
                'month_b' => 612,
                'sai_c' => 83,
                'month_c' => 612,
                'sai_d' => 83,
                'month_d' => 612
            ],
            [
                'id' => 186,
                'sai_a' => 83,
                'month_a' => 611,
                'sai_b' => 83,
                'month_b' => 611,
                'sai_c' => 83,
                'month_c' => 611,
                'sai_d' => 83,
                'month_d' => 611
            ],
            [
                'id' => 187,
                'sai_a' => 83,
                'month_a' => 610,
                'sai_b' => 83,
                'month_b' => 610,
                'sai_c' => 83,
                'month_c' => 610,
                'sai_d' => 83,
                'month_d' => 610
            ],
            [
                'id' => 188,
                'sai_a' => 82,
                'month_a' => 609,
                'sai_b' => 82,
                'month_b' => 609,
                'sai_c' => 82,
                'month_c' => 609,
                'sai_d' => 82,
                'month_d' => 609
            ],
            [
                'id' => 189,
                'sai_a' => 82,
                'month_a' => 608,
                'sai_b' => 82,
                'month_b' => 608,
                'sai_c' => 82,
                'month_c' => 608,
                'sai_d' => 82,
                'month_d' => 608
            ],
            [
                'id' => 190,
                'sai_a' => 81,
                'month_a' => 607,
                'sai_b' => 81,
                'month_b' => 607,
                'sai_c' => 81,
                'month_c' => 607,
                'sai_d' => 81,
                'month_d' => 607
            ],
            [
                'id' => 191,
                'sai_a' => 81,
                'month_a' => 606,
                'sai_b' => 81,
                'month_b' => 606,
                'sai_c' => 81,
                'month_c' => 606,
                'sai_d' => 81,
                'month_d' => 606
            ],
            [
                'id' => 192,
                'sai_a' => 80,
                'month_a' => 605,
                'sai_b' => 80,
                'month_b' => 605,
                'sai_c' => 80,
                'month_c' => 605,
                'sai_d' => 80,
                'month_d' => 605
            ],
            [
                'id' => 193,
                'sai_a' => 80,
                'month_a' => 604,
                'sai_b' => 80,
                'month_b' => 604,
                'sai_c' => 80,
                'month_c' => 604,
                'sai_d' => 80,
                'month_d' => 604
            ],
            [
                'id' => 194,
                'sai_a' => 80,
                'month_a' => 603,
                'sai_b' => 80,
                'month_b' => 603,
                'sai_c' => 80,
                'month_c' => 603,
                'sai_d' => 80,
                'month_d' => 603
            ],
            [
                'id' => 195,
                'sai_a' => 79,
                'month_a' => 602,
                'sai_b' => 79,
                'month_b' => 602,
                'sai_c' => 79,
                'month_c' => 602,
                'sai_d' => 79,
                'month_d' => 602
            ],
            [
                'id' => 196,
                'sai_a' => 79,
                'month_a' => 601,
                'sai_b' => 79,
                'month_b' => 601,
                'sai_c' => 79,
                'month_c' => 601,
                'sai_d' => 79,
                'month_d' => 601
            ],
            [
                'id' => 197,
                'sai_a' => 78,
                'month_a' => 600,
                'sai_b' => 78,
                'month_b' => 600,
                'sai_c' => 78,
                'month_c' => 600,
                'sai_d' => 78,
                'month_d' => 600
            ],
            [
                'id' => 198,
                'sai_a' => 78,
                'month_a' => 599,
                'sai_b' => 78,
                'month_b' => 599,
                'sai_c' => 78,
                'month_c' => 599,
                'sai_d' => 78,
                'month_d' => 599
            ],
            [
                'id' => 199,
                'sai_a' => 77,
                'month_a' => 598,
                'sai_b' => 77,
                'month_b' => 598,
                'sai_c' => 77,
                'month_c' => 598,
                'sai_d' => 77,
                'month_d' => 598
            ],
            [
                'id' => 200,
                'sai_a' => 77,
                'month_a' => 597,
                'sai_b' => 77,
                'month_b' => 597,
                'sai_c' => 77,
                'month_c' => 597,
                'sai_d' => 77,
                'month_d' => 597
            ]
        ]);

        DB::table('tbl_sstosai_16nv')->insert([
            [
                'id' => 201,
                'sai_a' => 77,
                'month_a' => 596,
                'sai_b' => 77,
                'month_b' => 596,
                'sai_c' => 77,
                'month_c' => 596,
                'sai_d' => 77,
                'month_d' => 596
            ],
            [
                'id' => 202,
                'sai_a' => 76,
                'month_a' => 595,
                'sai_b' => 76,
                'month_b' => 595,
                'sai_c' => 76,
                'month_c' => 595,
                'sai_d' => 76,
                'month_d' => 595
            ],
            [
                'id' => 203,
                'sai_a' => 76,
                'month_a' => 594,
                'sai_b' => 76,
                'month_b' => 594,
                'sai_c' => 76,
                'month_c' => 594,
                'sai_d' => 76,
                'month_d' => 594
            ],
            [
                'id' => 204,
                'sai_a' => 75,
                'month_a' => 593,
                'sai_b' => 75,
                'month_b' => 593,
                'sai_c' => 75,
                'month_c' => 593,
                'sai_d' => 75,
                'month_d' => 593
            ],
            [
                'id' => 205,
                'sai_a' => 75,
                'month_a' => 592,
                'sai_b' => 75,
                'month_b' => 592,
                'sai_c' => 75,
                'month_c' => 592,
                'sai_d' => 75,
                'month_d' => 592
            ],
            [
                'id' => 206,
                'sai_a' => 74,
                'month_a' => 591,
                'sai_b' => 74,
                'month_b' => 591,
                'sai_c' => 74,
                'month_c' => 591,
                'sai_d' => 74,
                'month_d' => 591
            ],
            [
                'id' => 207,
                'sai_a' => 74,
                'month_a' => 590,
                'sai_b' => 74,
                'month_b' => 590,
                'sai_c' => 74,
                'month_c' => 590,
                'sai_d' => 74,
                'month_d' => 590
            ],
            [
                'id' => 208,
                'sai_a' => 74,
                'month_a' => 589,
                'sai_b' => 74,
                'month_b' => 589,
                'sai_c' => 74,
                'month_c' => 589,
                'sai_d' => 74,
                'month_d' => 589
            ],
            [
                'id' => 209,
                'sai_a' => 73,
                'month_a' => 588,
                'sai_b' => 73,
                'month_b' => 588,
                'sai_c' => 73,
                'month_c' => 588,
                'sai_d' => 73,
                'month_d' => 588
            ],
            [
                'id' => 210,
                'sai_a' => 73,
                'month_a' => 587,
                'sai_b' => 73,
                'month_b' => 587,
                'sai_c' => 73,
                'month_c' => 587,
                'sai_d' => 73,
                'month_d' => 587
            ],
            [
                'id' => 211,
                'sai_a' => 72,
                'month_a' => 586,
                'sai_b' => 72,
                'month_b' => 586,
                'sai_c' => 72,
                'month_c' => 586,
                'sai_d' => 72,
                'month_d' => 586
            ],
            [
                'id' => 212,
                'sai_a' => 72,
                'month_a' => 585,
                'sai_b' => 72,
                'month_b' => 585,
                'sai_c' => 72,
                'month_c' => 585,
                'sai_d' => 72,
                'month_d' => 585
            ],
            [
                'id' => 213,
                'sai_a' => 72,
                'month_a' => 584,
                'sai_b' => 72,
                'month_b' => 584,
                'sai_c' => 72,
                'month_c' => 584,
                'sai_d' => 72,
                'month_d' => 584
            ],
            [
                'id' => 214,
                'sai_a' => 71,
                'month_a' => 583,
                'sai_b' => 71,
                'month_b' => 583,
                'sai_c' => 71,
                'month_c' => 583,
                'sai_d' => 71,
                'month_d' => 583
            ],
            [
                'id' => 215,
                'sai_a' => 71,
                'month_a' => 582,
                'sai_b' => 71,
                'month_b' => 582,
                'sai_c' => 71,
                'month_c' => 582,
                'sai_d' => 71,
                'month_d' => 582
            ],
            [
                'id' => 216,
                'sai_a' => 70,
                'month_a' => 581,
                'sai_b' => 70,
                'month_b' => 581,
                'sai_c' => 70,
                'month_c' => 581,
                'sai_d' => 70,
                'month_d' => 581
            ],
            [
                'id' => 217,
                'sai_a' => 70,
                'month_a' => 580,
                'sai_b' => 70,
                'month_b' => 580,
                'sai_c' => 70,
                'month_c' => 580,
                'sai_d' => 70,
                'month_d' => 580
            ],
            [
                'id' => 218,
                'sai_a' => 69,
                'month_a' => 579,
                'sai_b' => 69,
                'month_b' => 579,
                'sai_c' => 69,
                'month_c' => 579,
                'sai_d' => 69,
                'month_d' => 579
            ],
            [
                'id' => 219,
                'sai_a' => 69,
                'month_a' => 578,
                'sai_b' => 69,
                'month_b' => 578,
                'sai_c' => 69,
                'month_c' => 578,
                'sai_d' => 69,
                'month_d' => 578
            ],
            [
                'id' => 220,
                'sai_a' => 69,
                'month_a' => 577,
                'sai_b' => 69,
                'month_b' => 577,
                'sai_c' => 69,
                'month_c' => 577,
                'sai_d' => 68,
                'month_d' => 577
            ],
            [
                'id' => 221,
                'sai_a' => 68,
                'month_a' => 576,
                'sai_b' => 68,
                'month_b' => 576,
                'sai_c' => 68,
                'month_c' => 576,
                'sai_d' => 68,
                'month_d' => 576
            ],
            [
                'id' => 222,
                'sai_a' => 68,
                'month_a' => 575,
                'sai_b' => 68,
                'month_b' => 575,
                'sai_c' => 68,
                'month_c' => 575,
                'sai_d' => 67,
                'month_d' => 575
            ],
            [
                'id' => 223,
                'sai_a' => 67,
                'month_a' => 574,
                'sai_b' => 67,
                'month_b' => 574,
                'sai_c' => 67,
                'month_c' => 574,
                'sai_d' => 67,
                'month_d' => 574
            ],
            [
                'id' => 224,
                'sai_a' => 67,
                'month_a' => 573,
                'sai_b' => 67,
                'month_b' => 573,
                'sai_c' => 67,
                'month_c' => 573,
                'sai_d' => 67,
                'month_d' => 573
            ],
            [
                'id' => 225,
                'sai_a' => 67,
                'month_a' => 572,
                'sai_b' => 67,
                'month_b' => 572,
                'sai_c' => 67,
                'month_c' => 572,
                'sai_d' => 66,
                'month_d' => 572
            ],
            [
                'id' => 226,
                'sai_a' => 66,
                'month_a' => 571,
                'sai_b' => 66,
                'month_b' => 571,
                'sai_c' => 66,
                'month_c' => 571,
                'sai_d' => 65,
                'month_d' => 571
            ],
            [
                'id' => 227,
                'sai_a' => 66,
                'month_a' => 570,
                'sai_b' => 66,
                'month_b' => 570,
                'sai_c' => 66,
                'month_c' => 570,
                'sai_d' => 65,
                'month_d' => 570
            ],
            [
                'id' => 228,
                'sai_a' => 66,
                'month_a' => 569,
                'sai_b' => 66,
                'month_b' => 569,
                'sai_c' => 66,
                'month_c' => 569,
                'sai_d' => 64,
                'month_d' => 569
            ],
            [
                'id' => 229,
                'sai_a' => 65,
                'month_a' => 568,
                'sai_b' => 65,
                'month_b' => 568,
                'sai_c' => 65,
                'month_c' => 568,
                'sai_d' => 64,
                'month_d' => 568
            ],
            [
                'id' => 230,
                'sai_a' => 65,
                'month_a' => 567,
                'sai_b' => 65,
                'month_b' => 567,
                'sai_c' => 65,
                'month_c' => 567,
                'sai_d' => 64,
                'month_d' => 567
            ],
            [
                'id' => 231,
                'sai_a' => 64,
                'month_a' => 566,
                'sai_b' => 64,
                'month_b' => 566,
                'sai_c' => 64,
                'month_c' => 566,
                'sai_d' => 63,
                'month_d' => 566
            ],
            [
                'id' => 232,
                'sai_a' => 64,
                'month_a' => 565,
                'sai_b' => 64,
                'month_b' => 565,
                'sai_c' => 64,
                'month_c' => 565,
                'sai_d' => 63,
                'month_d' => 565
            ],
            [
                'id' => 233,
                'sai_a' => 64,
                'month_a' => 564,
                'sai_b' => 64,
                'month_b' => 564,
                'sai_c' => 64,
                'month_c' => 564,
                'sai_d' => 62,
                'month_d' => 564
            ],
            [
                'id' => 234,
                'sai_a' => 63,
                'month_a' => 563,
                'sai_b' => 63,
                'month_b' => 563,
                'sai_c' => 63,
                'month_c' => 563,
                'sai_d' => 62,
                'month_d' => 563
            ],
            [
                'id' => 235,
                'sai_a' => 63,
                'month_a' => 562,
                'sai_b' => 63,
                'month_b' => 562,
                'sai_c' => 63,
                'month_c' => 562,
                'sai_d' => 62,
                'month_d' => 562
            ],
            [
                'id' => 236,
                'sai_a' => 62,
                'month_a' => 561,
                'sai_b' => 62,
                'month_b' => 561,
                'sai_c' => 62,
                'month_c' => 561,
                'sai_d' => 61,
                'month_d' => 561
            ],
            [
                'id' => 237,
                'sai_a' => 62,
                'month_a' => 560,
                'sai_b' => 62,
                'month_b' => 560,
                'sai_c' => 62,
                'month_c' => 560,
                'sai_d' => 61,
                'month_d' => 560
            ],
            [
                'id' => 238,
                'sai_a' => 62,
                'month_a' => 559,
                'sai_b' => 62,
                'month_b' => 559,
                'sai_c' => 62,
                'month_c' => 559,
                'sai_d' => 60,
                'month_d' => 559
            ],
            [
                'id' => 239,
                'sai_a' => 61,
                'month_a' => 558,
                'sai_b' => 61,
                'month_b' => 558,
                'sai_c' => 61,
                'month_c' => 558,
                'sai_d' => 60,
                'month_d' => 558
            ],
            [
                'id' => 240,
                'sai_a' => 61,
                'month_a' => 557,
                'sai_b' => 61,
                'month_b' => 557,
                'sai_c' => 61,
                'month_c' => 557,
                'sai_d' => 59,
                'month_d' => 557
            ],
            [
                'id' => 241,
                'sai_a' => 60,
                'month_a' => 556,
                'sai_b' => 60,
                'month_b' => 556,
                'sai_c' => 60,
                'month_c' => 556,
                'sai_d' => 59,
                'month_d' => 556
            ],
            [
                'id' => 242,
                'sai_a' => 60,
                'month_a' => 555,
                'sai_b' => 60,
                'month_b' => 555,
                'sai_c' => 60,
                'month_c' => 555,
                'sai_d' => 59,
                'month_d' => 555
            ],
            [
                'id' => 243,
                'sai_a' => 59,
                'month_a' => 554,
                'sai_b' => 59,
                'month_b' => 554,
                'sai_c' => 59,
                'month_c' => 554,
                'sai_d' => 58,
                'month_d' => 554
            ],
            [
                'id' => 244,
                'sai_a' => 59,
                'month_a' => 553,
                'sai_b' => 59,
                'month_b' => 553,
                'sai_c' => 59,
                'month_c' => 553,
                'sai_d' => 58,
                'month_d' => 553
            ],
            [
                'id' => 245,
                'sai_a' => 59,
                'month_a' => 552,
                'sai_b' => 59,
                'month_b' => 552,
                'sai_c' => 59,
                'month_c' => 552,
                'sai_d' => 58,
                'month_d' => 552
            ],
            [
                'id' => 246,
                'sai_a' => 58,
                'month_a' => 551,
                'sai_b' => 58,
                'month_b' => 551,
                'sai_c' => 58,
                'month_c' => 551,
                'sai_d' => 57,
                'month_d' => 551
            ],
            [
                'id' => 247,
                'sai_a' => 58,
                'month_a' => 550,
                'sai_b' => 58,
                'month_b' => 550,
                'sai_c' => 58,
                'month_c' => 550,
                'sai_d' => 57,
                'month_d' => 550
            ],
            [
                'id' => 248,
                'sai_a' => 58,
                'month_a' => 549,
                'sai_b' => 58,
                'month_b' => 549,
                'sai_c' => 58,
                'month_c' => 549,
                'sai_d' => 57,
                'month_d' => 549
            ],
            [
                'id' => 249,
                'sai_a' => 57,
                'month_a' => 548,
                'sai_b' => 57,
                'month_b' => 548,
                'sai_c' => 57,
                'month_c' => 548,
                'sai_d' => 56,
                'month_d' => 548
            ],
            [
                'id' => 250,
                'sai_a' => 57,
                'month_a' => 547,
                'sai_b' => 57,
                'month_b' => 547,
                'sai_c' => 57,
                'month_c' => 547,
                'sai_d' => 56,
                'month_d' => 547
            ],
            [
                'id' => 251,
                'sai_a' => 57,
                'month_a' => 546,
                'sai_b' => 57,
                'month_b' => 546,
                'sai_c' => 57,
                'month_c' => 546,
                'sai_d' => 56,
                'month_d' => 546
            ],
            [
                'id' => 252,
                'sai_a' => 56,
                'month_a' => 545,
                'sai_b' => 56,
                'month_b' => 545,
                'sai_c' => 56,
                'month_c' => 545,
                'sai_d' => 55,
                'month_d' => 545
            ],
            [
                'id' => 253,
                'sai_a' => 56,
                'month_a' => 544,
                'sai_b' => 56,
                'month_b' => 544,
                'sai_c' => 56,
                'month_c' => 544,
                'sai_d' => 55,
                'month_d' => 544
            ],
            [
                'id' => 254,
                'sai_a' => 56,
                'month_a' => 543,
                'sai_b' => 56,
                'month_b' => 543,
                'sai_c' => 56,
                'month_c' => 543,
                'sai_d' => 54,
                'month_d' => 543
            ],
            [
                'id' => 255,
                'sai_a' => 55,
                'month_a' => 542,
                'sai_b' => 55,
                'month_b' => 542,
                'sai_c' => 55,
                'month_c' => 542,
                'sai_d' => 54,
                'month_d' => 542
            ],
            [
                'id' => 256,
                'sai_a' => 55,
                'month_a' => 541,
                'sai_b' => 55,
                'month_b' => 541,
                'sai_c' => 55,
                'month_c' => 541,
                'sai_d' => 53,
                'month_d' => 541
            ],
            [
                'id' => 257,
                'sai_a' => 54,
                'month_a' => 540,
                'sai_b' => 54,
                'month_b' => 540,
                'sai_c' => 54,
                'month_c' => 540,
                'sai_d' => 53,
                'month_d' => 540
            ],
            [
                'id' => 258,
                'sai_a' => 54,
                'month_a' => 539,
                'sai_b' => 54,
                'month_b' => 539,
                'sai_c' => 54,
                'month_c' => 539,
                'sai_d' => 52,
                'month_d' => 539
            ],
            [
                'id' => 259,
                'sai_a' => 53,
                'month_a' => 538,
                'sai_b' => 53,
                'month_b' => 538,
                'sai_c' => 53,
                'month_c' => 538,
                'sai_d' => 52,
                'month_d' => 538
            ],
            [
                'id' => 260,
                'sai_a' => 53,
                'month_a' => 537,
                'sai_b' => 53,
                'month_b' => 537,
                'sai_c' => 53,
                'month_c' => 537,
                'sai_d' => 51,
                'month_d' => 537
            ],
            [
                'id' => 261,
                'sai_a' => 52,
                'month_a' => 536,
                'sai_b' => 52,
                'month_b' => 536,
                'sai_c' => 52,
                'month_c' => 536,
                'sai_d' => 51,
                'month_d' => 536
            ],
            [
                'id' => 262,
                'sai_a' => 52,
                'month_a' => 535,
                'sai_b' => 52,
                'month_b' => 535,
                'sai_c' => 52,
                'month_c' => 535,
                'sai_d' => 0,
                'month_d' => 0
            ],
            [
                'id' => 263,
                'sai_a' => 51,
                'month_a' => 534,
                'sai_b' => 51,
                'month_b' => 534,
                'sai_c' => 51,
                'month_c' => 534,
                'sai_d' => 0,
                'month_d' => 0
            ],
            [
                'id' => 264,
                'sai_a' => 51,
                'month_a' => 533,
                'sai_b' => 51,
                'month_b' => 533,
                'sai_c' => 51,
                'month_c' => 533,
                'sai_d' => 0,
                'month_d' => 0
            ]
        ]);
    }
}